import {
  Curriculum,
  HSKLevelInfo,
  CurriculumUnit,
  Lesson,
  LessonSection,
  Vocabulary,
  GrammarPoint,
  QuizQuestion,
  LessonVocabulary,
} from '../types/curriculum';

export const HSK_CURRICULUM: Curriculum = {
  id: 'curriculum-hsk-3.0',
  name: 'Bentalk AI HSK-Aligned Structured Chinese Curriculum',
  version: 'hsk-3.0',
  language: 'vi',
  targetLanguage: 'zh-CN',
  description: 'Giáo trình tiếng Trung theo chuẩn HSK 3.0 với lộ trình toàn diện từ nhập môn đến thành thạo.',
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-03-18T00:00:00Z',
};

export const HSK_LEVELS_INFO: HSKLevelInfo[] = [
  {
    id: 'hsk-level-1',
    level: 1,
    title: 'HSK 1',
    nameZh: '一级 · Nhập môn',
    descriptionVi: 'Giao tiếp rất cơ bản trong đời sống hàng ngày',
    objectives: [
      'Nắm vững Pinyin và 4 thanh điệu',
      'Chào hỏi, giới thiệu bản thân và giao tiếp xã giao cơ bản',
      'Nói về gia đình, thời gian, ăn uống và mua sắm đơn giản',
      'Xây dựng phản xạ nghe-nói bằng câu ngắn và mẫu câu nền',
    ],
    estimatedHours: 40,
    totalLessons: 8,
    totalUnits: 3,
    totalVocabulary: 150,
    totalGrammarPoints: 15,
    order: 1,
  },
  {
    id: 'hsk-level-2',
    level: 2,
    title: 'HSK 2',
    nameZh: '二级 · Sơ cấp',
    descriptionVi: 'Giao tiếp đơn giản và trực tiếp về các chủ đề quen thuộc',
    objectives: [
      'Mô tả thói quen, thời gian và hoạt động đang diễn ra',
      'Hỏi đường, di chuyển và xử lý tình huống đời thường',
      'So sánh sản phẩm, hỏi giá và đưa ra lựa chọn',
      'Mô tả sức khỏe và đưa ra lời khuyên đơn giản',
    ],
    estimatedHours: 60,
    totalLessons: 4,
    totalUnits: 3,
    totalVocabulary: 300,
    totalGrammarPoints: 25,
    prerequisites: [1],
    order: 2,
  },
  {
    id: 'hsk-level-3',
    level: 3,
    title: 'HSK 3',
    nameZh: '三级 · Trung cấp 1',
    descriptionVi: 'Hoàn thành nhiệm vụ giao tiếp cơ bản trong đời sống, học tập và công việc',
    objectives: [
      'Kể trải nghiệm và xử lý tình huống du lịch độc lập',
      'Trao đổi về công việc, phỏng vấn và cân bằng cuộc sống',
      'Nêu ý kiến, giải thích nguyên nhân-kết quả và phản hồi lịch sự',
      'Mở rộng hội thoại từ câu đơn sang diễn đạt có liên kết',
    ],
    estimatedHours: 90,
    totalLessons: 6,
    totalUnits: 2,
    totalVocabulary: 600,
    totalGrammarPoints: 35,
    prerequisites: [2],
    order: 3,
  },
  {
    id: 'hsk-level-4',
    level: 4,
    title: 'HSK 4',
    nameZh: '四级 · Trung cấp 2',
    descriptionVi: 'Thảo luận nhiều chủ đề với cách diễn đạt tương đối chuẩn mực',
    objectives: [
      'Thảo luận đời sống, xã hội và môi trường bằng câu phức',
      'Giao tiếp nơi công sở, làm rõ yêu cầu và phản hồi lịch sự',
      'Trình bày quan điểm có dẫn chứng và liên kết logic',
      'Điều chỉnh văn phong theo bối cảnh giao tiếp',
    ],
    estimatedHours: 120,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 1200,
    totalGrammarPoints: 45,
    prerequisites: [3],
    order: 4,
  },
  {
    id: 'hsk-level-5',
    level: 5,
    title: 'HSK 5',
    nameZh: '五级 · Cao cấp 1',
    descriptionVi: 'Đọc báo, xem phim và trình bày quan điểm về chủ đề trừu tượng',
    objectives: [
      'Đọc và tóm tắt thông tin từ báo chí, truyền thông',
      'Phân tích lập luận và phân biệt dữ kiện với nhận định',
      'Thuyết trình, đàm phán và diễn đạt quan điểm chuyên nghiệp',
    ],
    estimatedHours: 180,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 2500,
    totalGrammarPoints: 60,
    prerequisites: [4],
    order: 5,
  },
  {
    id: 'hsk-level-6',
    level: 6,
    title: 'HSK 6',
    nameZh: '六级 · Thành thạo',
    descriptionVi: 'Hiểu sâu và diễn đạt linh hoạt, gần mức người bản ngữ',
    objectives: [
      'Phân tích văn bản học thuật và xây dựng lập luận chặt chẽ',
      'Làm chủ thành ngữ, sắc thái và khác biệt văn phong',
      'Giao tiếp chuyên sâu trong học thuật, xã hội và thương mại',
    ],
    estimatedHours: 240,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 5000,
    totalGrammarPoints: 80,
    prerequisites: [5],
    order: 6,
  },
];

export const CURRICULUM_UNITS: CurriculumUnit[] = [
  // HSK 1 Units
  {
    id: 'unit-hsk1-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    title: 'Lời chào và Giao tiếp mở đầu',
    titleZh: '问候与基本礼仪',
    description: 'Học cách chào hỏi, giới thiệu bản thân và xã giao lịch sự khi lần đầu gặp gỡ.',
    objectives: ['Chào hỏi lịch thiệp', 'Hỏi thăm sức khỏe', 'Cảm ơn và xin lỗi'],
    estimatedMinutes: 45,
    lessonCount: 4,
    icon: 'Hand',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    title: 'Giới thiệu bản thân & Quốc tịch',
    titleZh: '自我介绍与国籍',
    description: 'Nói về bản thân, hỏi tên họ, xuất xứ và nghề nghiệp cơ bản.',
    objectives: ['Hỏi và trả lời tên', 'Nói về quốc tịch và đất nước', 'Giới thiệu nghề nghiệp'],
    estimatedMinutes: 50,
    lessonCount: 2,
    icon: 'User',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    title: 'Số đếm, Mua sắm & Giá cả',
    titleZh: '数字与购物',
    description: 'Làm quen số đếm 1-100, hỏi giá tiền và gọi món trong quán ăn.',
    objectives: ['Đếm số và thanh toán', 'Hỏi giá bao nhiêu tiền', 'Gọi món đơn giản'],
    estimatedMinutes: 55,
    lessonCount: 2,
    icon: 'ShoppingBag',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 2 Units
  {
    id: 'unit-hsk2-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    title: 'Sinh hoạt hàng ngày & Giờ giấc',
    titleZh: '日常生活与时间',
    description: 'Mô tả thói quen sinh hoạt mỗi ngày, thức dậy, đi làm và hỏi giờ chuẩn xác.',
    objectives: ['Nói về thời gian trong ngày', 'Mô tả thói quen sinh hoạt', 'Sử dụng phó từ chỉ tần suất'],
    estimatedMinutes: 50,
    lessonCount: 2,
    icon: 'Clock',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    title: 'Mua sắm & So sánh',
    titleZh: '购物与比较',
    description: 'So sánh sản phẩm, hỏi giá, kích thước và đưa ra lựa chọn phù hợp.',
    objectives: ['Dùng 比 để so sánh', 'Hỏi giá và kích thước', 'Diễn đạt lựa chọn đơn giản'],
    estimatedMinutes: 55,
    lessonCount: 1,
    icon: 'ShoppingBag',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 3,
    title: 'Sức khỏe & Lời khuyên',
    titleZh: '健康与建议',
    description: 'Mô tả triệu chứng đơn giản và đưa ra lời khuyên trong tình huống đời thường.',
    objectives: ['Mô tả cảm giác không khỏe', 'Dùng 应该 để đưa lời khuyên', 'Nói về nghỉ ngơi và uống thuốc'],
    estimatedMinutes: 60,
    lessonCount: 1,
    icon: 'HeartPulse',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 3 Units
  {
    id: 'unit-hsk3-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    title: 'Du lịch & Trải nghiệm',
    titleZh: '旅游与经历',
    description: 'Kể về trải nghiệm du lịch, tham quan danh lam thắng cảnh và đặt phòng.',
    objectives: ['Sử dụng trợ từ 过 chỉ trải nghiệm', 'Đặt phòng và yêu cầu dịch vụ', 'Miêu tả phong cảnh'],
    estimatedMinutes: 60,
    lessonCount: 4,
    icon: 'Plane',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk3-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 2,
    title: 'Công việc & Phỏng vấn',
    titleZh: '职场与面试',
    description: 'Thảo luận về kinh nghiệm làm việc, kỹ năng nghề nghiệp và phỏng vấn.',
    objectives: ['Giới thiệu kỹ năng chuyên môn', 'Nói về kế hoạch nghề nghiệp', 'Sử dụng liên từ nhân quả'],
    estimatedMinutes: 65,
    lessonCount: 2,
    icon: 'Briefcase',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 4 Unit
  {
    id: 'unit-hsk4-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    title: 'Giao tiếp công sở, xã hội & môi trường',
    titleZh: '职场沟通、社会与环境',
    description: 'Xử lý giao tiếp công sở và thảo luận về thay đổi xã hội, môi trường.',
    objectives: ['Diễn đạt sắc thái tâm lý tinh tế', 'Sử dụng câu chữ 把 thuần thục'],
    estimatedMinutes: 70,
    lessonCount: 4,
    icon: 'Heart',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 5 Unit
  {
    id: 'unit-hsk5-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    title: 'Truyền thông, kinh doanh & đàm phán',
    titleZh: '媒体、商务与谈判',
    description: 'Đọc tin, phân tích lập luận và luyện ngôn ngữ thương mại, đàm phán.',
    objectives: ['Đọc văn bản phong cách nghị luận', 'Sử dụng từ Hán Việt cao cấp'],
    estimatedMinutes: 75,
    lessonCount: 4,
    icon: 'TrendingUp',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 6 Unit
  {
    id: 'unit-hsk6-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    title: 'Học thuật, lập luận & sắc thái ngôn ngữ',
    titleZh: '学术论证与语言细微差别',
    description: 'Phân tích văn bản học thuật, thành ngữ và khác biệt sắc thái văn phong.',
    objectives: ['Làm chủ thành ngữ cổ và điển cố', 'Biểu đạt luận điểm sắc sảo'],
    estimatedMinutes: 80,
    lessonCount: 4,
    icon: 'Sparkles',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];
