import {
  Curriculum,
  HSKLevelInfo,
  CurriculumUnit,
  Lesson,
  LessonSection,
  Vocabulary,
  GrammarPoint,
  QuizQuestion,
  LessonVocabulary,
} from '../types/curriculum';

export const HSK_CURRICULUM: Curriculum = {
  id: 'curriculum-hsk-3.0',
  name: 'Bentalk AI HSK-Aligned Structured Chinese Curriculum',
  version: 'hsk-3.0',
  language: 'vi',
  targetLanguage: 'zh-CN',
  description: 'Giáo trình tiếng Trung theo chuẩn HSK 3.0 với lộ trình toàn diện từ nhập môn đến thành thạo.',
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-03-18T00:00:00Z',
};

export const HSK_LEVELS_INFO: HSKLevelInfo[] = [
  {
    id: 'hsk-level-1',
    level: 1,
    title: 'HSK 1',
    nameZh: '一级 · Nhập môn',
    descriptionVi: 'Chào hỏi & đời sống cơ bản',
    objectives: [
      'Nắm vững Pinyin và 4 thanh điệu',
      'Chào hỏi, giới thiệu bản thân và giao tiếp xã giao cơ bản',
      'Nói về gia đình, thời gian, ăn uống và mua sắm đơn giản',
      'Xây dựng phản xạ nghe-nói bằng câu ngắn và mẫu câu nền',
    ],
    estimatedHours: 40,
    totalLessons: 8,
    totalUnits: 3,
    totalVocabulary: 150,
    totalGrammarPoints: 15,
    order: 1,
  },
  {
    id: 'hsk-level-2',
    level: 2,
    title: 'HSK 2',
    nameZh: '二级 · Sơ cấp',
    descriptionVi: 'Giao tiếp hàng ngày, mua sắm & tình huống thực tế',
    objectives: [
      'Mô tả thói quen, thời gian và hoạt động đang diễn ra',
      'Hỏi đường, di chuyển và xử lý tình huống đời thường',
      'So sánh sản phẩm, hỏi giá và đưa ra lựa chọn',
      'Mô tả sức khỏe và đưa ra lời khuyên đơn giản',
    ],
    estimatedHours: 60,
    totalLessons: 4,
    totalUnits: 3,
    totalVocabulary: 300,
    totalGrammarPoints: 25,
    prerequisites: [1],
    order: 2,
  },
  {
    id: 'hsk-level-3',
    level: 3,
    title: 'HSK 3',
    nameZh: '三级 · Trung cấp 1',
    descriptionVi: 'Du lịch, công việc & biểu đạt',
    objectives: [
      'Kể trải nghiệm và xử lý tình huống du lịch độc lập',
      'Trao đổi về công việc, phỏng vấn và cân bằng cuộc sống',
      'Nêu ý kiến, giải thích nguyên nhân-kết quả và phản hồi lịch sự',
      'Mở rộng hội thoại từ câu đơn sang diễn đạt có liên kết',
    ],
    estimatedHours: 90,
    totalLessons: 4,
    totalUnits: 2,
    totalVocabulary: 600,
    totalGrammarPoints: 35,
    prerequisites: [2],
    order: 3,
  },
  {
    id: 'hsk-level-4',
    level: 4,
    title: 'HSK 4',
    nameZh: '四级 · Trung cấp 2',
    descriptionVi: 'Thảo luận trôi chảy đa chủ đề',
    objectives: [
      'Thảo luận đời sống, xã hội và môi trường bằng câu phức',
      'Giao tiếp nơi công sở, làm rõ yêu cầu và phản hồi lịch sự',
      'Trình bày quan điểm có dẫn chứng và liên kết logic',
      'Điều chỉnh văn phong theo bối cảnh giao tiếp',
    ],
    estimatedHours: 120,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 1200,
    totalGrammarPoints: 45,
    prerequisites: [3],
    order: 4,
  },
  {
    id: 'hsk-level-5',
    level: 5,
    title: 'HSK 5',
    nameZh: '五级 · Cao cấp 1',
    descriptionVi: 'Đọc báo & xem phim tiếng Trung',
    objectives: [
      'Đọc và tóm tắt thông tin từ báo chí, truyền thông',
      'Phân tích lập luận và phân biệt dữ kiện với nhận định',
      'Thuyết trình, đàm phán và diễn đạt quan điểm chuyên nghiệp',
    ],
    estimatedHours: 180,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 2500,
    totalGrammarPoints: 60,
    prerequisites: [4],
    order: 5,
  },
  {
    id: 'hsk-level-6',
    level: 6,
    title: 'HSK 6',
    nameZh: '六级 · Thành thạo',
    descriptionVi: 'Làm chủ ngôn ngữ chuyên sâu',
    objectives: [
      'Phân tích văn bản học thuật và xây dựng lập luận chặt chẽ',
      'Làm chủ thành ngữ, sắc thái và khác biệt văn phong',
      'Giao tiếp chuyên sâu trong học thuật, xã hội và thương mại',
    ],
    estimatedHours: 240,
    totalLessons: 4,
    totalUnits: 1,
    totalVocabulary: 5000,
    totalGrammarPoints: 80,
    prerequisites: [5],
    order: 6,
  },
];

export const CURRICULUM_UNITS: CurriculumUnit[] = [
  // HSK 1 Units
  {
    id: 'unit-hsk1-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    title: 'Lời chào và Giao tiếp mở đầu',
    titleZh: '问候与基本礼仪',
    description: 'Học cách chào hỏi, giới thiệu bản thân và xã giao lịch sự khi lần đầu gặp gỡ.',
    objectives: ['Chào hỏi lịch thiệp', 'Hỏi thăm sức khỏe', 'Cảm ơn và xin lỗi'],
    estimatedMinutes: 45,
    lessonCount: 4,
    icon: 'Hand',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    title: 'Giới thiệu bản thân & Quốc tịch',
    titleZh: '自我介绍与国籍',
    description: 'Nói về bản thân, hỏi tên họ, xuất xứ và nghề nghiệp cơ bản.',
    objectives: ['Hỏi và trả lời tên', 'Nói về quốc tịch và đất nước', 'Giới thiệu nghề nghiệp'],
    estimatedMinutes: 50,
    lessonCount: 2,
    icon: 'User',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    title: 'Số đếm, Mua sắm & Giá cả',
    titleZh: '数字与购物',
    description: 'Làm quen số đếm 1-100, hỏi giá tiền và gọi món trong quán ăn.',
    objectives: ['Đếm số và thanh toán', 'Hỏi giá bao nhiêu tiền', 'Gọi món đơn giản'],
    estimatedMinutes: 55,
    lessonCount: 2,
    icon: 'ShoppingBag',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 2 Units
  {
    id: 'unit-hsk2-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    title: 'Sinh hoạt hàng ngày & Giờ giấc',
    titleZh: '日常生活与时间',
    description: 'Mô tả thói quen sinh hoạt mỗi ngày, thức dậy, đi làm và hỏi giờ chuẩn xác.',
    objectives: ['Nói về thời gian trong ngày', 'Mô tả thói quen sinh hoạt', 'Sử dụng phó từ chỉ tần suất'],
    estimatedMinutes: 50,
    lessonCount: 2,
    icon: 'Clock',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    title: 'Hỏi đường & Di chuyển',
    titleZh: '问路与交通',
    description: 'Chỉ đường, hỏi phương hướng và đi tàu điện ngầm, xe buýt, taxi.',
    objectives: ['Hỏi đường đi', 'Phương hướng trái phải trước sau', 'Phương tiện giao thông công cộng'],
    estimatedMinutes: 55,
    lessonCount: 1,
    icon: 'Compass',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 3,
    title: 'Thời tiết & Dự định',
    titleZh: '天气与计划',
    description: 'Nói về thời tiết bốn mùa và lên kế hoạch cuối tuần cùng bạn bè.',
    objectives: ['Miêu tả thời tiết nóng lạnh mưa nắng', 'Nói về dự định tương lai (想, 要)', 'Lên lịch hẹn'],
    estimatedMinutes: 60,
    lessonCount: 1,
    icon: 'CloudSun',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 3 Units
  {
    id: 'unit-hsk3-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    title: 'Du lịch & Trải nghiệm',
    titleZh: '旅游与经历',
    description: 'Kể về trải nghiệm du lịch, tham quan danh lam thắng cảnh và đặt phòng.',
    objectives: ['Sử dụng trợ từ 过 chỉ trải nghiệm', 'Đặt phòng và yêu cầu dịch vụ', 'Miêu tả phong cảnh'],
    estimatedMinutes: 60,
    lessonCount: 2,
    icon: 'Plane',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk3-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 2,
    title: 'Công việc & Phỏng vấn',
    titleZh: '职场与面试',
    description: 'Thảo luận về kinh nghiệm làm việc, kỹ năng nghề nghiệp và phỏng vấn.',
    objectives: ['Giới thiệu kỹ năng chuyên môn', 'Nói về kế hoạch nghề nghiệp', 'Sử dụng liên từ nhân quả'],
    estimatedMinutes: 65,
    lessonCount: 4,
    icon: 'Briefcase',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 4 Unit
  {
    id: 'unit-hsk4-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    title: 'Các mối quan hệ & Giao tiếp xã hội',
    titleZh: '人际关系与情感',
    description: 'Bàn luận sâu sắc về tình bạn, tình yêu và cách ứng xử trong xã hội hiện đại.',
    objectives: ['Diễn đạt sắc thái tâm lý tinh tế', 'Sử dụng câu chữ 把 thuần thục'],
    estimatedMinutes: 70,
    lessonCount: 4,
    icon: 'Heart',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 5 Unit
  {
    id: 'unit-hsk5-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    title: 'Kinh tế & Xu hướng Công nghệ',
    titleZh: '科技与商业趋势',
    description: 'Đọc hiểu bài báo thương mại, phân tích xu hướng thị trường số.',
    objectives: ['Đọc văn bản phong cách nghị luận', 'Sử dụng từ Hán Việt cao cấp'],
    estimatedMinutes: 75,
    lessonCount: 4,
    icon: 'TrendingUp',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 6 Unit
  {
    id: 'unit-hsk6-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    title: 'Triết lý Văn hóa & Thành ngữ Cổ',
    titleZh: '中国哲学与成语',
    description: 'Thưởng thức văn hóa truyền thống, thành ngữ 4 chữ và tư tưởng phương Đông.',
    objectives: ['Làm chủ thành ngữ cổ và điển cố', 'Biểu đạt luận điểm sắc sảo'],
    estimatedMinutes: 80,
    lessonCount: 4,
    icon: 'Sparkles',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];
