import {
  Curriculum,
  HSKLevelInfo,
  CurriculumUnit,
  Lesson,
  LessonSection,
  Vocabulary,
  GrammarPoint,
  QuizQuestion,
  LessonVocabulary,
} from '../types/curriculum';

export const HSK_CURRICULUM: Curriculum = {
  id: 'curriculum-hsk-3.0',
  name: 'HanziAI HSK-Aligned Structured Chinese Curriculum',
  version: 'hsk-3.0',
  language: 'vi',
  targetLanguage: 'zh-CN',
  description: 'Giáo trình tiếng Trung theo chuẩn HSK 3.0 với lộ trình toàn diện từ nhập môn đến thành thạo.',
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-03-18T00:00:00Z',
};

export const HSK_LEVELS_INFO: HSKLevelInfo[] = [
  {
    id: 'hsk-level-1',
    level: 1,
    title: 'HSK 1',
    nameZh: '一级 · Nhập môn',
    descriptionVi: 'Giao tiếp cơ bản, chào hỏi, giới thiệu bản thân, mua sắm đơn giản và số đếm.',
    objectives: [
      'Nắm vững hệ thống ngữ âm Pinyin và 4 thanh điệu',
      'Chào hỏi, cảm ơn, xin lỗi và tạm biệt chuẩn mực',
      'Giới thiệu tên, tuổi, quốc tịch và nghề nghiệp',
      'Đếm số, hỏi giờ, hỏi ngày tháng và hỏi giá cả cơ bản',
    ],
    estimatedHours: 40,
    totalLessons: 9,
    totalUnits: 3,
    totalVocabulary: 150,
    totalGrammarPoints: 15,
    order: 1,
  },
  {
    id: 'hsk-level-2',
    level: 2,
    title: 'HSK 2',
    nameZh: '二级 · Sơ cấp',
    descriptionVi: 'Trao đổi tự tin về cuộc sống thường nhật, gia đình, sở thích, thời tiết và phương hướng.',
    objectives: [
      'Mô tả thói quen sinh hoạt hàng ngày và thời gian biểu',
      'Hỏi đường, chỉ đường và sử dụng phương tiện giao thông',
      'Nói về sở thích, thể thao, đồ ăn thức uống',
      'Miêu tả trạng thái thời tiết và biểu đạt cảm xúc đơn giản',
    ],
    estimatedHours: 60,
    totalLessons: 6,
    totalUnits: 3,
    totalVocabulary: 300,
    totalGrammarPoints: 25,
    prerequisites: [1],
    order: 2,
  },
  {
    id: 'hsk-level-3',
    level: 3,
    title: 'HSK 3',
    nameZh: '三级 · Trung cấp 1',
    descriptionVi: 'Du lịch độc lập khắp Trung Quốc, làm việc cơ bản và diễn đạt suy nghĩ cá nhân trôi chảy.',
    objectives: [
      'Đặt phòng khách sạn, vé máy bay và xử lý tình huống du lịch',
      'Miêu tả ngoại hình tính cách và quan điểm cá nhân',
      'Sử dụng các cấu trúc liên từ phức hợp (vì...nên, tuy...nhưng)',
      'Tham gia thảo luận về kế hoạch công việc và học tập',
    ],
    estimatedHours: 90,
    totalLessons: 4,
    totalUnits: 2,
    totalVocabulary: 600,
    totalGrammarPoints: 35,
    prerequisites: [2],
    order: 3,
  },
  {
    id: 'hsk-level-4',
    level: 4,
    title: 'HSK 4',
    nameZh: '四级 · Trung cấp 2',
    descriptionVi: 'Thảo luận rộng rãi nhiều chủ đề đời sống, xã hội, xem tin tức và giao tiếp tự nhiên.',
    objectives: [
      'Hiểu bản tin thời sự, phim tài liệu ngắn',
      'Trình bày ý kiến mạch lạc và tranh luận nhẹ nhàng',
      'Nắm vững câu chữ 把, câu chữ 被 và câu phức logic',
    ],
    estimatedHours: 120,
    totalLessons: 2,
    totalUnits: 1,
    totalVocabulary: 1200,
    totalGrammarPoints: 45,
    prerequisites: [3],
    order: 4,
  },
  {
    id: 'hsk-level-5',
    level: 5,
    title: 'HSK 5',
    nameZh: '五级 · Cao cấp 1',
    descriptionVi: 'Đọc báo chí, thưởng thức phim ảnh không phụ đề và thuyết trình chuyên môn.',
    objectives: [
      'Đọc các tác phẩm văn học, bài luận học thuật',
      'Thuyết trình và viết báo cáo công sở chuyên nghiệp',
      'Hiểu sắc thái biểu cảm và ẩn ý trong tiếng Hán',
    ],
    estimatedHours: 180,
    totalLessons: 2,
    totalUnits: 1,
    totalVocabulary: 2500,
    totalGrammarPoints: 60,
    prerequisites: [4],
    order: 5,
  },
  {
    id: 'hsk-level-6',
    level: 6,
    title: 'HSK 6',
    nameZh: '六级 · Thành thạo',
    descriptionVi: 'Làm chủ ngôn ngữ, biểu đạt sắc thái tinh tế và phản xạ như người bản xứ.',
    objectives: [
      'Hiểu sâu các thành ngữ Thành ngữ (成语) và văn hóa Hán tự',
      'Giao tiếp tự nhiên trong mọi bối cảnh học thuật và thương mại',
      'Viết bài nghị luận và bình luận chuyên sâu',
    ],
    estimatedHours: 240,
    totalLessons: 2,
    totalUnits: 1,
    totalVocabulary: 5000,
    totalGrammarPoints: 80,
    prerequisites: [5],
    order: 6,
  },
];

export const CURRICULUM_UNITS: CurriculumUnit[] = [
  // HSK 1 Units
  {
    id: 'unit-hsk1-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    title: 'Lời chào và Giao tiếp mở đầu',
    titleZh: '问候与基本礼仪',
    description: 'Học cách chào hỏi, giới thiệu bản thân và xã giao lịch sự khi lần đầu gặp gỡ.',
    objectives: ['Chào hỏi lịch thiệp', 'Hỏi thăm sức khỏe', 'Cảm ơn và xin lỗi'],
    estimatedMinutes: 45,
    lessonCount: 3,
    icon: 'Hand',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    title: 'Giới thiệu bản thân & Quốc tịch',
    titleZh: '自我介绍与国籍',
    description: 'Nói về bản thân, hỏi tên họ, xuất xứ và nghề nghiệp cơ bản.',
    objectives: ['Hỏi và trả lời tên', 'Nói về quốc tịch và đất nước', 'Giới thiệu nghề nghiệp'],
    estimatedMinutes: 50,
    lessonCount: 3,
    icon: 'User',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk1-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    title: 'Số đếm, Mua sắm & Giá cả',
    titleZh: '数字与购物',
    description: 'Làm quen số đếm 1-100, hỏi giá tiền và gọi món trong quán ăn.',
    objectives: ['Đếm số và thanh toán', 'Hỏi giá bao nhiêu tiền', 'Gọi món đơn giản'],
    estimatedMinutes: 55,
    lessonCount: 3,
    icon: 'ShoppingBag',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 2 Units
  {
    id: 'unit-hsk2-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    title: 'Sinh hoạt hàng ngày & Giờ giấc',
    titleZh: '日常生活与时间',
    description: 'Mô tả thói quen sinh hoạt mỗi ngày, thức dậy, đi làm và hỏi giờ chuẩn xác.',
    objectives: ['Nói về thời gian trong ngày', 'Mô tả thói quen sinh hoạt', 'Sử dụng phó từ chỉ tần suất'],
    estimatedMinutes: 50,
    lessonCount: 2,
    icon: 'Clock',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    title: 'Hỏi đường & Di chuyển',
    titleZh: '问路与交通',
    description: 'Chỉ đường, hỏi phương hướng và đi tàu điện ngầm, xe buýt, taxi.',
    objectives: ['Hỏi đường đi', 'Phương hướng trái phải trước sau', 'Phương tiện giao thông công cộng'],
    estimatedMinutes: 55,
    lessonCount: 2,
    icon: 'Compass',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk2-u3',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 3,
    title: 'Thời tiết & Dự định',
    titleZh: '天气与计划',
    description: 'Nói về thời tiết bốn mùa và lên kế hoạch cuối tuần cùng bạn bè.',
    objectives: ['Miêu tả thời tiết nóng lạnh mưa nắng', 'Nói về dự định tương lai (想, 要)', 'Lên lịch hẹn'],
    estimatedMinutes: 60,
    lessonCount: 2,
    icon: 'CloudSun',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 3 Units
  {
    id: 'unit-hsk3-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    title: 'Du lịch & Trải nghiệm',
    titleZh: '旅游与经历',
    description: 'Kể về trải nghiệm du lịch, tham quan danh lam thắng cảnh và đặt phòng.',
    objectives: ['Sử dụng trợ từ 过 chỉ trải nghiệm', 'Đặt phòng và yêu cầu dịch vụ', 'Miêu tả phong cảnh'],
    estimatedMinutes: 60,
    lessonCount: 2,
    icon: 'Plane',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'unit-hsk3-u2',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 2,
    title: 'Công việc & Phỏng vấn',
    titleZh: '职场与面试',
    description: 'Thảo luận về kinh nghiệm làm việc, kỹ năng nghề nghiệp và phỏng vấn.',
    objectives: ['Giới thiệu kỹ năng chuyên môn', 'Nói về kế hoạch nghề nghiệp', 'Sử dụng liên từ nhân quả'],
    estimatedMinutes: 65,
    lessonCount: 2,
    icon: 'Briefcase',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 4 Unit
  {
    id: 'unit-hsk4-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    title: 'Các mối quan hệ & Giao tiếp xã hội',
    titleZh: '人际关系与情感',
    description: 'Bàn luận sâu sắc về tình bạn, tình yêu và cách ứng xử trong xã hội hiện đại.',
    objectives: ['Diễn đạt sắc thái tâm lý tinh tế', 'Sử dụng câu chữ 把 thuần thục'],
    estimatedMinutes: 70,
    lessonCount: 2,
    icon: 'Heart',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 5 Unit
  {
    id: 'unit-hsk5-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    title: 'Kinh tế & Xu hướng Công nghệ',
    titleZh: '科技与商业趋势',
    description: 'Đọc hiểu bài báo thương mại, phân tích xu hướng thị trường số.',
    objectives: ['Đọc văn bản phong cách nghị luận', 'Sử dụng từ Hán Việt cao cấp'],
    estimatedMinutes: 75,
    lessonCount: 2,
    icon: 'TrendingUp',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 6 Unit
  {
    id: 'unit-hsk6-u1',
    curriculumId: 'curriculum-hsk-3.0',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    title: 'Triết lý Văn hóa & Thành ngữ Cổ',
    titleZh: '中国哲学与成语',
    description: 'Thưởng thức văn hóa truyền thống, thành ngữ 4 chữ và tư tưởng phương Đông.',
    objectives: ['Làm chủ thành ngữ cổ và điển cố', 'Biểu đạt luận điểm sắc sảo'],
    estimatedMinutes: 80,
    lessonCount: 2,
    icon: 'Sparkles',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];
