import { GrammarPoint } from '../types/curriculum';

const g = (id: string, level: 1|2|3|4|5|6, title: string, pattern: string, explanationVi: string, examples: {chinese:string;pinyin:string;translationVi:string}[], commonMistakes: string[], difficulty: 'beginner'|'intermediate'|'advanced'): GrammarPoint => ({
  id, level, title, pattern, explanationVi, examples, commonMistakes, difficulty,
  createdAt: '2026-09-28T00:00:00Z', updatedAt: '2026-09-28T00:00:00Z'
});

export const DEEP_EXPANDED_GRAMMAR: GrammarPoint[] = [
 g('grammar-hsk1-de-01',1,'Sở hữu với 的','A + 的 + B','Dùng 的 để nói B thuộc về A.',[{chinese:'这是我的家人。',pinyin:'Zhè shì wǒ de jiārén.',translationVi:'Đây là gia đình của tôi.'},{chinese:'她是我哥哥的朋友。',pinyin:'Tā shì wǒ gēge de péngyou.',translationVi:'Cô ấy là bạn của anh trai tôi.'}],['Bỏ 的 khi cần làm rõ quan hệ sở hữu.'],'beginner'),
 g('grammar-hsk1-de-02',1,'Đề nghị với 吧','V + 吧','吧 làm câu đề nghị hoặc gợi ý nhẹ nhàng hơn.',[{chinese:'明天下午见面吧。',pinyin:'Míngtiān xiàwǔ jiànmiàn ba.',translationVi:'Chiều mai gặp nhau nhé.'},{chinese:'我们三点见吧。',pinyin:'Wǒmen sān diǎn jiàn ba.',translationVi:'Ba giờ chúng ta gặp nhé.'}],['Dùng 吧 như một từ chỉ thời gian.'],'beginner'),
 g('grammar-hsk2-de-01',2,'So sánh với 比','A 比 B + tính từ','Dùng 比 để nói A có mức độ cao/thấp hơn B.',[{chinese:'这个比那个便宜。',pinyin:'Zhège bǐ nàge piányi.',translationVi:'Cái này rẻ hơn cái kia.'},{chinese:'今天比昨天忙。',pinyin:'Jīntiān bǐ zuótiān máng.',translationVi:'Hôm nay bận hơn hôm qua.'}],['Không thêm 很 sau tính từ trong mẫu so sánh cơ bản.'],'beginner'),
 g('grammar-hsk2-de-02',2,'Lời khuyên với 应该','S + 应该 + V','应该 diễn đạt điều nên làm.',[{chinese:'你应该多休息。',pinyin:'Nǐ yīnggāi duō xiūxi.',translationVi:'Bạn nên nghỉ ngơi nhiều hơn.'},{chinese:'我觉得你应该早点睡。',pinyin:'Wǒ juéde nǐ yīnggāi zǎodiǎn shuì.',translationVi:'Tôi nghĩ bạn nên ngủ sớm hơn.'}],['Nhầm 应该 với 必须; 必须 mang tính bắt buộc mạnh hơn.'],'beginner'),
 g('grammar-hsk3-de-01',3,'Mở rộng với 除了…以外…','除了 A 以外，B 还…','Nêu thêm một đối tượng hoặc hoạt động ngoài A.',[{chinese:'除了工作以外，我还想陪家人。',pinyin:'Chúle gōngzuò yǐwài, wǒ hái xiǎng péi jiārén.',translationVi:'Ngoài công việc, tôi còn muốn dành thời gian cho gia đình.'},{chinese:'除了中文以外，她还学习英文。',pinyin:'Chúle Zhōngwén yǐwài, tā hái xuéxí Yīngwén.',translationVi:'Ngoài tiếng Trung, cô ấy còn học tiếng Anh.'}],['Quên 还 khi muốn nhấn mạnh ý bổ sung.'],'intermediate'),
 g('grammar-hsk3-de-02',3,'Nguyên nhân và kết quả','因为 A，所以 B','Liên kết nguyên nhân với kết quả.',[{chinese:'因为工作很忙，所以我最近压力很大。',pinyin:'Yīnwèi gōngzuò hěn máng, suǒyǐ wǒ zuìjìn yālì hěn dà.',translationVi:'Vì công việc rất bận nên gần đây tôi rất áp lực.'},{chinese:'因为下雨，所以我们改时间了。',pinyin:'Yīnwèi xiàyǔ, suǒyǐ wǒmen gǎi shíjiān le.',translationVi:'Vì trời mưa nên chúng tôi đổi thời gian.'}],['Không đảo lộn nguyên nhân và kết quả.'],'intermediate'),
 g('grammar-hsk4-de-01',4,'Nhấn mạnh kép với 不但…而且…','不但 A，而且 B','Liên kết hai đặc điểm cùng được nhấn mạnh.',[{chinese:'他不但沟通清楚，而且反应很快。',pinyin:'Tā bùdàn gōutōng qīngchu, érqiě fǎnyìng hěn kuài.',translationVi:'Anh ấy không chỉ giao tiếp rõ mà phản ứng còn rất nhanh.'},{chinese:'这个方案不但环保，而且成本低。',pinyin:'Zhège fāngàn bùdàn huánbǎo, érqiě chéngběn dī.',translationVi:'Phương án này không chỉ thân thiện môi trường mà chi phí còn thấp.'}],['Vế sau phải bổ sung ý tương ứng với vế trước.'],'intermediate'),
 g('grammar-hsk4-de-02',4,'Làm rõ với 确认','先 + V + 一下','Dùng 一下 làm yêu cầu mềm hơn khi kiểm tra hoặc xác nhận.',[{chinese:'我们先确认一下信息。',pinyin:'Wǒmen xiān quèrèn yíxià xìnxī.',translationVi:'Chúng ta xác nhận thông tin trước nhé.'},{chinese:'请确认一下时间。',pinyin:'Qǐng quèrèn yíxià shíjiān.',translationVi:'Vui lòng xác nhận lại thời gian.'}],['Hiểu 一下 là “một lần” trong mọi ngữ cảnh.'],'intermediate'),
 g('grammar-hsk5-de-01',5,'Phân biệt với 区分','区分 A 和 B','Dùng 区分 để phân biệt hai khái niệm hoặc đối tượng.',[{chinese:'我们应该区分信息和观点。',pinyin:'Wǒmen yīnggāi qūfēn xìnxī hé guāndiǎn.',translationVi:'Chúng ta nên phân biệt thông tin và quan điểm.'},{chinese:'阅读时要区分事实和评论。',pinyin:'Yuèdú shí yào qūfēn shìshí hé pínglùn.',translationVi:'Khi đọc cần phân biệt sự thật và bình luận.'}],['Dùng 区别 như động từ thay cho 区分 trong mọi trường hợp.'],'advanced'),
 g('grammar-hsk5-de-02',5,'Điều kiện trong đàm phán','如果 A，就 B','Nêu điều kiện và kết quả có thể xảy ra.',[{chinese:'如果价格合适，我们就可以合作。',pinyin:'Rúguǒ jiàgé héshì, wǒmen jiù kěyǐ hézuò.',translationVi:'Nếu giá phù hợp thì chúng ta có thể hợp tác.'},{chinese:'如果双方同意，就可以签合同。',pinyin:'Rúguǒ shuāngfāng tóngyì, jiù kěyǐ qiān hétóng.',translationVi:'Nếu hai bên đồng ý thì có thể ký hợp đồng.'}],['Dùng 如果 cho mệnh đề kết quả thay vì điều kiện.'],'advanced'),
 g('grammar-hsk6-de-01',6,'Lập luận với 因此','A，因此 B','因此 nối kết luận hoặc hệ quả trong văn phong trang trọng.',[{chinese:'证据不足，因此这个结论还需要进一步验证。',pinyin:'Zhèngjù bùzú, yīncǐ zhège jiélùn hái xūyào jìnyíbù yànzhèng.',translationVi:'Bằng chứng chưa đủ, vì vậy kết luận này cần được kiểm chứng thêm.'},{chinese:'数据发生变化，因此原来的判断需要调整。',pinyin:'Shùjù fāshēng biànhuà, yīncǐ yuánlái de pànduàn xūyào tiáozhěng.',translationVi:'Dữ liệu thay đổi, vì vậy nhận định ban đầu cần được điều chỉnh.'}],['Dùng 因此 trong mọi hội thoại thân mật thay cho 所以.'],'advanced'),
 g('grammar-hsk6-de-02',6,'Sắc thái với 虽然…但是…','虽然 A，但是 B','Thừa nhận một điều nhưng nhấn mạnh ý đối lập.',[{chinese:'虽然这个观点有道理，但是证据还不够充分。',pinyin:'Suīrán zhège guāndiǎn yǒu dàolǐ, dànshì zhèngjù hái búgòu chōngfèn.',translationVi:'Mặc dù quan điểm này có lý, nhưng bằng chứng vẫn chưa đủ.'},{chinese:'虽然表达不同，但是意思基本一样。',pinyin:'Suīrán biǎodá bùtóng, dànshì yìsi jīběn yíyàng.',translationVi:'Mặc dù cách diễn đạt khác nhau nhưng ý nghĩa cơ bản giống nhau.'}],['Bỏ vế đối lập khiến cấu trúc chưa hoàn chỉnh.'],'advanced'),
];