import { Vocabulary, LessonVocabulary } from '../types/curriculum';

const now = '2026-09-28T00:00:00Z';

export const EXPANDED_LESSON_VOCABULARY: Vocabulary[] = [
  // HSK 1
  { id:'vocab-exp-hsk1-family-01', hanzi:'家人', pinyin:'jiārén', meaningVi:'người nhà, thành viên gia đình', meaningEn:'family member', partOfSpeech:'Danh từ', hskLevel:1, exampleSentence:'我的家人都很好。', examplePinyin:'Wǒ de jiārén dōu hěn hǎo.', exampleTranslation:'Gia đình tôi đều khỏe.', tags:['family','core'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-family-02', hanzi:'哥哥', pinyin:'gēge', meaningVi:'anh trai', meaningEn:'older brother', partOfSpeech:'Danh từ', hskLevel:1, exampleSentence:'我有一个哥哥。', examplePinyin:'Wǒ yǒu yí ge gēge.', exampleTranslation:'Tôi có một anh trai.', tags:['family'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-family-03', hanzi:'妹妹', pinyin:'mèimei', meaningVi:'em gái', meaningEn:'younger sister', partOfSpeech:'Danh từ', hskLevel:1, exampleSentence:'妹妹在家。', examplePinyin:'Mèimei zài jiā.', exampleTranslation:'Em gái ở nhà.', tags:['family'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-family-04', hanzi:'的', pinyin:'de', meaningVi:'trợ từ sở hữu', meaningEn:'possessive particle', partOfSpeech:'Trợ từ', hskLevel:1, exampleSentence:'这是我的书。', examplePinyin:'Zhè shì wǒ de shū.', exampleTranslation:'Đây là sách của tôi.', tags:['grammar','possession'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-time-01', hanzi:'今天', pinyin:'jīntiān', meaningVi:'hôm nay', meaningEn:'today', partOfSpeech:'Danh từ thời gian', hskLevel:1, exampleSentence:'今天星期三。', examplePinyin:'Jīntiān xīngqīsān.', exampleTranslation:'Hôm nay là thứ Tư.', tags:['time'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-time-02', hanzi:'明天', pinyin:'míngtiān', meaningVi:'ngày mai', meaningEn:'tomorrow', partOfSpeech:'Danh từ thời gian', hskLevel:1, exampleSentence:'明天见！', examplePinyin:'Míngtiān jiàn!', exampleTranslation:'Hẹn gặp ngày mai!', tags:['time'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-time-03', hanzi:'星期', pinyin:'xīngqī', meaningVi:'tuần; thứ trong tuần', meaningEn:'week', partOfSpeech:'Danh từ', hskLevel:1, exampleSentence:'今天星期几？', examplePinyin:'Jīntiān xīngqī jǐ?', exampleTranslation:'Hôm nay thứ mấy?', tags:['time'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk1-time-04', hanzi:'见面', pinyin:'jiànmiàn', meaningVi:'gặp mặt', meaningEn:'meet', partOfSpeech:'Động từ', hskLevel:1, exampleSentence:'我们下午见面。', examplePinyin:'Wǒmen xiàwǔ jiànmiàn.', exampleTranslation:'Chúng ta gặp nhau buổi chiều.', tags:['time','meeting'], createdAt:now, updatedAt:now },
  // HSK 2
  { id:'vocab-exp-hsk2-shop-01', hanzi:'便宜', pinyin:'piányi', meaningVi:'rẻ', meaningEn:'cheap', partOfSpeech:'Tính từ', hskLevel:2, exampleSentence:'这个比较便宜。', examplePinyin:'Zhège bǐjiào piányi.', exampleTranslation:'Cái này khá rẻ.', tags:['shopping'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-shop-02', hanzi:'贵', pinyin:'guì', meaningVi:'đắt', meaningEn:'expensive', partOfSpeech:'Tính từ', hskLevel:2, exampleSentence:'这个太贵了。', examplePinyin:'Zhège tài guì le.', exampleTranslation:'Cái này đắt quá.', tags:['shopping'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-shop-03', hanzi:'尺寸', pinyin:'chǐcùn', meaningVi:'kích thước, cỡ', meaningEn:'size', partOfSpeech:'Danh từ', hskLevel:2, exampleSentence:'有大一点的尺寸吗？', examplePinyin:'Yǒu dà yìdiǎn de chǐcùn ma?', exampleTranslation:'Có cỡ lớn hơn một chút không?', tags:['shopping'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-shop-04', hanzi:'比较', pinyin:'bǐjiào', meaningVi:'khá; tương đối; so sánh', meaningEn:'relatively; compare', partOfSpeech:'Phó từ', hskLevel:2, exampleSentence:'这个比较好。', examplePinyin:'Zhège bǐjiào hǎo.', exampleTranslation:'Cái này khá tốt.', tags:['comparison'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-health-01', hanzi:'休息', pinyin:'xiūxi', meaningVi:'nghỉ ngơi', meaningEn:'rest', partOfSpeech:'Động từ', hskLevel:2, exampleSentence:'你应该多休息。', examplePinyin:'Nǐ yīnggāi duō xiūxi.', exampleTranslation:'Bạn nên nghỉ ngơi nhiều hơn.', tags:['health'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-health-02', hanzi:'头疼', pinyin:'tóuténg', meaningVi:'đau đầu', meaningEn:'headache', partOfSpeech:'Động từ', hskLevel:2, exampleSentence:'我今天头疼。', examplePinyin:'Wǒ jīntiān tóuténg.', exampleTranslation:'Hôm nay tôi đau đầu.', tags:['health'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-health-03', hanzi:'应该', pinyin:'yīnggāi', meaningVi:'nên, cần phải', meaningEn:'should', partOfSpeech:'Động từ năng nguyện', hskLevel:2, exampleSentence:'你应该早点睡。', examplePinyin:'Nǐ yīnggāi zǎodiǎn shuì.', exampleTranslation:'Bạn nên ngủ sớm hơn.', tags:['health','grammar'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk2-health-04', hanzi:'药', pinyin:'yào', meaningVi:'thuốc', meaningEn:'medicine', partOfSpeech:'Danh từ', hskLevel:2, exampleSentence:'记得吃药。', examplePinyin:'Jìde chī yào.', exampleTranslation:'Nhớ uống thuốc.', tags:['health'], createdAt:now, updatedAt:now },
  // HSK 3
  { id:'vocab-exp-hsk3-work-01', hanzi:'压力', pinyin:'yālì', meaningVi:'áp lực', meaningEn:'pressure', partOfSpeech:'Danh từ', hskLevel:3, exampleSentence:'最近工作压力很大。', examplePinyin:'Zuìjìn gōngzuò yālì hěn dà.', exampleTranslation:'Gần đây áp lực công việc rất lớn.', tags:['work'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-work-02', hanzi:'平衡', pinyin:'pínghéng', meaningVi:'cân bằng', meaningEn:'balance', partOfSpeech:'Động từ/Danh từ', hskLevel:3, exampleSentence:'我们要平衡工作和生活。', examplePinyin:'Wǒmen yào pínghéng gōngzuò hé shēnghuó.', exampleTranslation:'Chúng ta cần cân bằng công việc và cuộc sống.', tags:['work-life'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-work-03', hanzi:'除了', pinyin:'chúle', meaningVi:'ngoài... ra', meaningEn:'besides; except', partOfSpeech:'Giới từ', hskLevel:3, exampleSentence:'除了工作，我还喜欢运动。', examplePinyin:'Chúle gōngzuò, wǒ hái xǐhuan yùndòng.', exampleTranslation:'Ngoài công việc, tôi còn thích thể thao.', tags:['grammar','work-life'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-work-04', hanzi:'安排', pinyin:'ānpái', meaningVi:'sắp xếp', meaningEn:'arrange', partOfSpeech:'Động từ', hskLevel:3, exampleSentence:'我会安排好时间。', examplePinyin:'Wǒ huì ānpái hǎo shíjiān.', exampleTranslation:'Tôi sẽ sắp xếp thời gian ổn thỏa.', tags:['work'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-opinion-01', hanzi:'觉得', pinyin:'juéde', meaningVi:'cảm thấy, cho rằng', meaningEn:'feel; think', partOfSpeech:'Động từ', hskLevel:3, exampleSentence:'我觉得这个办法不错。', examplePinyin:'Wǒ juéde zhège bànfǎ búcuò.', exampleTranslation:'Tôi thấy cách này khá tốt.', tags:['opinion'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-opinion-02', hanzi:'办法', pinyin:'bànfǎ', meaningVi:'cách, biện pháp', meaningEn:'method; solution', partOfSpeech:'Danh từ', hskLevel:3, exampleSentence:'我们需要想一个办法。', examplePinyin:'Wǒmen xūyào xiǎng yí ge bànfǎ.', exampleTranslation:'Chúng ta cần nghĩ ra một cách.', tags:['problem-solving'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-opinion-03', hanzi:'原因', pinyin:'yuányīn', meaningVi:'nguyên nhân', meaningEn:'reason; cause', partOfSpeech:'Danh từ', hskLevel:3, exampleSentence:'你知道原因吗？', examplePinyin:'Nǐ zhīdào yuányīn ma?', exampleTranslation:'Bạn biết nguyên nhân không?', tags:['opinion'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk3-opinion-04', hanzi:'看法', pinyin:'kànfǎ', meaningVi:'quan điểm, cách nhìn', meaningEn:'view; opinion', partOfSpeech:'Danh từ', hskLevel:3, exampleSentence:'我想听听你的看法。', examplePinyin:'Wǒ xiǎng tīngting nǐ de kànfǎ.', exampleTranslation:'Tôi muốn nghe quan điểm của bạn.', tags:['opinion'], createdAt:now, updatedAt:now },
  // HSK 4
  { id:'vocab-exp-hsk4-comm-01', hanzi:'沟通', pinyin:'gōutōng', meaningVi:'giao tiếp, trao đổi', meaningEn:'communicate', partOfSpeech:'Động từ', hskLevel:4, exampleSentence:'有效沟通很重要。', examplePinyin:'Yǒuxiào gōutōng hěn zhòngyào.', exampleTranslation:'Giao tiếp hiệu quả rất quan trọng.', tags:['work'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-comm-02', hanzi:'误会', pinyin:'wùhuì', meaningVi:'hiểu lầm', meaningEn:'misunderstanding', partOfSpeech:'Danh từ/Động từ', hskLevel:4, exampleSentence:'我们之间有一个误会。', examplePinyin:'Wǒmen zhījiān yǒu yí ge wùhuì.', exampleTranslation:'Giữa chúng ta có một hiểu lầm.', tags:['communication'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-comm-03', hanzi:'明确', pinyin:'míngquè', meaningVi:'rõ ràng, xác định', meaningEn:'clear; definite', partOfSpeech:'Tính từ', hskLevel:4, exampleSentence:'请明确说明你的要求。', examplePinyin:'Qǐng míngquè shuōmíng nǐ de yāoqiú.', exampleTranslation:'Hãy nói rõ yêu cầu của bạn.', tags:['communication'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-comm-04', hanzi:'要求', pinyin:'yāoqiú', meaningVi:'yêu cầu', meaningEn:'requirement; request', partOfSpeech:'Danh từ/Động từ', hskLevel:4, exampleSentence:'客户提出了新的要求。', examplePinyin:'Kèhù tíchū le xīn de yāoqiú.', exampleTranslation:'Khách hàng đưa ra yêu cầu mới.', tags:['work'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-env-01', hanzi:'环境', pinyin:'huánjìng', meaningVi:'môi trường', meaningEn:'environment', partOfSpeech:'Danh từ', hskLevel:4, exampleSentence:'保护环境人人有责。', examplePinyin:'Bǎohù huánjìng rénrén yǒu zé.', exampleTranslation:'Bảo vệ môi trường là trách nhiệm của mọi người.', tags:['environment'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-env-02', hanzi:'影响', pinyin:'yǐngxiǎng', meaningVi:'ảnh hưởng', meaningEn:'influence; impact', partOfSpeech:'Động từ/Danh từ', hskLevel:4, exampleSentence:'交通会影响生活质量。', examplePinyin:'Jiāotōng huì yǐngxiǎng shēnghuó zhìliàng.', exampleTranslation:'Giao thông có thể ảnh hưởng chất lượng cuộc sống.', tags:['environment'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-env-03', hanzi:'减少', pinyin:'jiǎnshǎo', meaningVi:'giảm bớt', meaningEn:'reduce', partOfSpeech:'Động từ', hskLevel:4, exampleSentence:'我们应该减少塑料使用。', examplePinyin:'Wǒmen yīnggāi jiǎnshǎo sùliào shǐyòng.', exampleTranslation:'Chúng ta nên giảm sử dụng nhựa.', tags:['environment'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk4-env-04', hanzi:'城市化', pinyin:'chéngshìhuà', meaningVi:'đô thị hóa', meaningEn:'urbanization', partOfSpeech:'Danh từ', hskLevel:4, exampleSentence:'城市化带来了很多变化。', examplePinyin:'Chéngshìhuà dàilái le hěn duō biànhuà.', exampleTranslation:'Đô thị hóa mang lại nhiều thay đổi.', tags:['society'], createdAt:now, updatedAt:now },
  // HSK 5
  { id:'vocab-exp-hsk5-media-01', hanzi:'报道', pinyin:'bàodào', meaningVi:'bản tin, đưa tin', meaningEn:'report', partOfSpeech:'Danh từ/Động từ', hskLevel:5, exampleSentence:'这篇报道引起了关注。', examplePinyin:'Zhè piān bàodào yǐnqǐ le guānzhù.', exampleTranslation:'Bài đưa tin này thu hút sự chú ý.', tags:['media'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-media-02', hanzi:'观点', pinyin:'guāndiǎn', meaningVi:'quan điểm', meaningEn:'viewpoint', partOfSpeech:'Danh từ', hskLevel:5, exampleSentence:'作者提出了不同的观点。', examplePinyin:'Zuòzhě tíchū le bùtóng de guāndiǎn.', exampleTranslation:'Tác giả đưa ra một quan điểm khác.', tags:['media','critical-thinking'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-media-03', hanzi:'证据', pinyin:'zhèngjù', meaningVi:'bằng chứng', meaningEn:'evidence', partOfSpeech:'Danh từ', hskLevel:5, exampleSentence:'这个观点需要更多证据。', examplePinyin:'Zhège guāndiǎn xūyào gèng duō zhèngjù.', exampleTranslation:'Quan điểm này cần thêm bằng chứng.', tags:['critical-thinking'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-media-04', hanzi:'概括', pinyin:'gàikuò', meaningVi:'khái quát, tóm tắt', meaningEn:'summarize', partOfSpeech:'Động từ', hskLevel:5, exampleSentence:'请概括文章的主要内容。', examplePinyin:'Qǐng gàikuò wénzhāng de zhǔyào nèiróng.', exampleTranslation:'Hãy tóm tắt nội dung chính của bài.', tags:['reading'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-business-01', hanzi:'谈判', pinyin:'tánpàn', meaningVi:'đàm phán', meaningEn:'negotiate', partOfSpeech:'Động từ/Danh từ', hskLevel:5, exampleSentence:'双方正在进行谈判。', examplePinyin:'Shuāngfāng zhèngzài jìnxíng tánpàn.', exampleTranslation:'Hai bên đang tiến hành đàm phán.', tags:['business'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-business-02', hanzi:'合作', pinyin:'hézuò', meaningVi:'hợp tác', meaningEn:'cooperate', partOfSpeech:'Động từ/Danh từ', hskLevel:5, exampleSentence:'我们希望长期合作。', examplePinyin:'Wǒmen xīwàng chángqī hézuò.', exampleTranslation:'Chúng tôi hy vọng hợp tác lâu dài.', tags:['business'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-business-03', hanzi:'条件', pinyin:'tiáojiàn', meaningVi:'điều kiện', meaningEn:'condition; terms', partOfSpeech:'Danh từ', hskLevel:5, exampleSentence:'双方正在讨论合作条件。', examplePinyin:'Shuāngfāng zhèngzài tǎolùn hézuò tiáojiàn.', exampleTranslation:'Hai bên đang thảo luận điều kiện hợp tác.', tags:['business'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk5-business-04', hanzi:'达成', pinyin:'dáchéng', meaningVi:'đạt được', meaningEn:'reach; achieve', partOfSpeech:'Động từ', hskLevel:5, exampleSentence:'双方最终达成了协议。', examplePinyin:'Shuāngfāng zuìzhōng dáchéng le xiéyì.', exampleTranslation:'Cuối cùng hai bên đã đạt được thỏa thuận.', tags:['business'], createdAt:now, updatedAt:now },
  // HSK 6
  { id:'vocab-exp-hsk6-academic-01', hanzi:'论证', pinyin:'lùnzhèng', meaningVi:'lập luận, chứng minh', meaningEn:'argumentation', partOfSpeech:'Động từ/Danh từ', hskLevel:6, exampleSentence:'作者通过数据进行论证。', examplePinyin:'Zuòzhě tōngguò shùjù jìnxíng lùnzhèng.', exampleTranslation:'Tác giả lập luận bằng dữ liệu.', tags:['academic'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-academic-02', hanzi:'结构', pinyin:'jiégòu', meaningVi:'cấu trúc', meaningEn:'structure', partOfSpeech:'Danh từ', hskLevel:6, exampleSentence:'文章的结构很清楚。', examplePinyin:'Wénzhāng de jiégòu hěn qīngchu.', exampleTranslation:'Cấu trúc bài viết rất rõ.', tags:['academic'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-academic-03', hanzi:'推理', pinyin:'tuīlǐ', meaningVi:'suy luận', meaningEn:'reasoning', partOfSpeech:'Danh từ/Động từ', hskLevel:6, exampleSentence:'这种推理需要更多依据。', examplePinyin:'Zhè zhǒng tuīlǐ xūyào gèng duō yījù.', exampleTranslation:'Kiểu suy luận này cần thêm căn cứ.', tags:['academic'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-academic-04', hanzi:'依据', pinyin:'yījù', meaningVi:'căn cứ, cơ sở', meaningEn:'basis; evidence', partOfSpeech:'Danh từ', hskLevel:6, exampleSentence:'这个结论缺少可靠依据。', examplePinyin:'Zhège jiélùn quēshǎo kěkào yījù.', exampleTranslation:'Kết luận này thiếu căn cứ đáng tin cậy.', tags:['academic'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-nuance-01', hanzi:'语境', pinyin:'yǔjìng', meaningVi:'ngữ cảnh', meaningEn:'context', partOfSpeech:'Danh từ', hskLevel:6, exampleSentence:'词语的意思要结合语境理解。', examplePinyin:'Cíyǔ de yìsi yào jiéhé yǔjìng lǐjiě.', exampleTranslation:'Nghĩa của từ cần được hiểu theo ngữ cảnh.', tags:['nuance'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-nuance-02', hanzi:'细微', pinyin:'xìwēi', meaningVi:'tinh tế, nhỏ nhưng khó nhận ra', meaningEn:'subtle', partOfSpeech:'Tính từ', hskLevel:6, exampleSentence:'两个词之间有细微差别。', examplePinyin:'Liǎng ge cí zhījiān yǒu xìwēi chābié.', exampleTranslation:'Hai từ có khác biệt tinh tế.', tags:['nuance'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-nuance-03', hanzi:'准确', pinyin:'zhǔnquè', meaningVi:'chính xác', meaningEn:'accurate', partOfSpeech:'Tính từ', hskLevel:6, exampleSentence:'请选择最准确的表达。', examplePinyin:'Qǐng xuǎnzé zuì zhǔnquè de biǎodá.', exampleTranslation:'Hãy chọn cách diễn đạt chính xác nhất.', tags:['nuance'], createdAt:now, updatedAt:now },
  { id:'vocab-exp-hsk6-nuance-04', hanzi:'表达', pinyin:'biǎodá', meaningVi:'biểu đạt, diễn đạt', meaningEn:'express', partOfSpeech:'Động từ/Danh từ', hskLevel:6, exampleSentence:'他的表达很自然。', examplePinyin:'Tā de biǎodá hěn zìrán.', exampleTranslation:'Cách diễn đạt của anh ấy rất tự nhiên.', tags:['nuance'], createdAt:now, updatedAt:now },
];

export const EXPANDED_LESSON_VOCABULARY_MAP: LessonVocabulary[] = [
  ...['family','time'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk1-u1-l${topic==='family'?3:4}-${topic==='family'?'family':'daily-time'}`,vocabularyId:`vocab-exp-hsk1-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
  ...['shop','health'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk2-u1-l${topic==='shop'?3:4}-${topic==='shop'?'shopping':'health'}`,vocabularyId:`vocab-exp-hsk2-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
  ...['work','opinion'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk3-u1-l${topic==='work'?3:4}-${topic==='work'?'work-life':'opinions'}`,vocabularyId:`vocab-exp-hsk3-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
  ...['comm','env'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk4-u1-l${topic==='comm'?3:4}-${topic==='comm'?'communication':'environment'}`,vocabularyId:`vocab-exp-hsk4-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
  ...['media','business'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk5-u1-l${topic==='media'?3:4}-${topic}`,vocabularyId:`vocab-exp-hsk5-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
  ...['academic','nuance'].flatMap((topic) => Array.from({length:4},(_,i)=>({lessonId:`lesson-hsk6-u1-l${topic==='academic'?3:4}-${topic}`,vocabularyId:`vocab-exp-hsk6-${topic}-${String(i+1).padStart(2,'0')}`,order:i+1,isCore:true}))),
];
