import {
  Lesson,
  LessonSection,
  QuizQuestion,
  LessonVocabulary,
  DialogueLine,
} from '../types/curriculum';

export const ALL_CURRICULUM_LESSONS: Lesson[] = [
  // ===================== HSK 1 =====================
  // Unit 1
  {
    id: 'lesson-hsk1-u1-l1',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    slug: 'hsk1-u1-l1-greetings',
    title: 'Chào hỏi cơ bản',
    titleZh: '问好与致谢',
    description: 'Học cách chào hỏi, cảm ơn và tạm biệt một cách tự nhiên, chuẩn mực và lịch sự.',
    objectives: [
      'Biết cách chào người khác bằng 你好 và kính ngữ 您好',
      'Nói lời cảm ơn (谢谢) và đáp lại khiêm tốn (不客气)',
      'Chào tạm biệt đối phương chuẩn xác (再见)',
    ],
    estimatedMinutes: 12,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u1-l2',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    slug: 'hsk1-u1-l2-how-are-you',
    title: 'Hỏi thăm sức khỏe & Đại từ nghi vấn 吗',
    titleZh: '身体好吗',
    description: 'Biết cách hỏi thăm sức khỏe người khác và sử dụng trợ từ nghi vấn 吗 để tạo câu hỏi.',
    objectives: [
      'Sử dụng cấu trúc 你好吗？ để hỏi thăm sức khỏe',
      'Trả lời bằng phó từ 很 (rất): 我很好 (Tôi rất khỏe)',
      'Nắm vững trợ từ nghi vấn 吗 ở cuối câu trần thuật',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 2
  {
    id: 'lesson-hsk1-u2-l3',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    slug: 'hsk1-u2-l3-what-is-your-name',
    title: 'Bạn tên là gì?',
    titleZh: '你叫什么名字',
    description: 'Làm quen với đại từ nghi vấn 什么 và mẫu câu hỏi tên họ trong tiếng Trung.',
    objectives: [
      'Hỏi tên người đối diện bằng 你叫什么名字？',
      'Tự tin giới thiệu họ tên bản thân bằng 我叫...',
      'Phân biệt cách xưng hô bạn bè và người lớn tuổi',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l2',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u2-l4',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 4,
    slug: 'hsk1-u2-l4-nationality',
    title: 'Quốc tịch & Câu phán đoán với 是',
    titleZh: '你是哪国人',
    description: 'Sử dụng động từ phán đoán 是 để giới thiệu quốc tịch, quê hương và xuất thân.',
    objectives: [
      'Hỏi quốc tịch người khác bằng 你是哪国人？',
      'Nói quốc tịch bản thân: 我是越南人 / 我是中国人',
      'Thành thạo cấu trúc phán đoán A 是 B',
    ],
    estimatedMinutes: 16,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l3',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 3
  {
    id: 'lesson-hsk1-u3-l5',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 5,
    slug: 'hsk1-u3-l5-eating-and-drinking',
    title: 'Ăn uống & Gọi món cơ bản',
    titleZh: '你想吃什么',
    description: 'Hỏi về sở thích ăn uống, mời người khác dùng trà và gọi món đơn giản.',
    objectives: [
      'Sử dụng động từ 吃 (ăn) và 喝 (uống)',
      'Hỏi người khác muốn ăn gì (你想吃什么？)',
      'Mời nước lịch sự (请喝茶)',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l4',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u3-l6',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 6,
    slug: 'hsk1-u3-l6-how-much-money',
    title: 'Hỏi giá tiền & Mua sắm',
    titleZh: '这个多少钱',
    description: 'Học cách hỏi giá cả hàng hóa, con số tiền tệ và hoàn tất thanh toán.',
    objectives: [
      'Hỏi giá bằng 這個多少錢？ (Cái này bao nhiêu tiền?)',
      'Hiểu đơn vị tiền tệ cơ bản (块 / 元)',
      'Thương lượng giá đơn giản khi đi chợ',
    ],
    estimatedMinutes: 18,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u3-l5',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },


  // HSK 1 Extension — Unit 2
  {
    id: 'lesson-hsk1-u2-l7', unitId: 'unit-hsk1-u2', levelId: 'hsk-level-1', levelNumber: 1, order: 5,
    slug: 'hsk1-u2-l7-family-and-home', title: 'Gia đình & Nhà của tôi', titleZh: '这是我的家',
    description: 'Giới thiệu gia đình và nhà ở bằng những câu gần gũi, đồng thời luyện mẫu sở hữu 的.',
    objectives: ['Gọi tên thành viên gia đình cơ bản', 'Dùng 的 để nói "của tôi/của bạn"', 'Tự giới thiệu gia đình bằng 3–4 câu đơn giản'],
    estimatedMinutes: 16, difficulty: 'easy', status: 'published', isPublished: true, isRequired: true, prerequisiteLessonId: 'lesson-hsk1-u2-l4',
    completionRule: 'all_required_and_quiz', passingScore: 80, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u2-l8', unitId: 'unit-hsk1-u2', levelId: 'hsk-level-1', levelNumber: 1, order: 6,
    slug: 'hsk1-u2-l8-days-and-time', title: 'Ngày trong tuần & Lịch hẹn', titleZh: '今天星期几',
    description: 'Hỏi thứ, nói hôm nay/ngày mai và tạo một cuộc hẹn đơn giản với bạn bè.',
    objectives: ['Hỏi và trả lời thứ trong tuần', 'Phân biệt 今天 và 明天', 'Đặt một lịch hẹn ngắn bằng tiếng Trung'],
    estimatedMinutes: 17, difficulty: 'easy', status: 'published', isPublished: true, isRequired: true, prerequisiteLessonId: 'lesson-hsk1-u2-l7',
    completionRule: 'all_required_and_quiz', passingScore: 80, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-18T00:00:00Z',
  },
  // HSK 1 Extension — Unit 3
  {
    id: 'lesson-hsk1-u3-l9', unitId: 'unit-hsk1-u3', levelId: 'hsk-level-1', levelNumber: 1, order: 7,
    slug: 'hsk1-u3-l9-hobbies', title: 'Sở thích & Cuối tuần', titleZh: '你喜欢做什么',
    description: 'Biến vốn từ HSK1 thành hội thoại đời thực: nói mình thích gì và lên ý tưởng cho cuối tuần.',
    objectives: ['Dùng 喜欢 để nói sở thích', 'Kết hợp 喜欢 + hoạt động như 看电影, 听音乐', 'Nói 4–5 câu về cuối tuần của bản thân'],
    estimatedMinutes: 18, difficulty: 'easy', status: 'published', isPublished: true, isRequired: true, prerequisiteLessonId: 'lesson-hsk1-u3-l6',
    completionRule: 'all_required_and_quiz', passingScore: 80, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 2 =====================
  {
    id: 'lesson-hsk2-u1-l1',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    slug: 'hsk2-u1-l1-daily-routine',
    title: 'Thói quen sinh hoạt mỗi ngày',
    titleZh: '我每天早上七点起床',
    description: 'Mô tả thói quen sinh hoạt hàng ngày, thức dậy, ăn sáng và tập thể dục.',
    objectives: [
      'Nói giờ chuẩn xác và sắp xếp thời gian biểu',
      'Sử dụng động từ ly hợp 起床 (thức dậy), 跑步 (chạy bộ)',
      'Miêu tả chuỗi hành động thường nhật',
    ],
    estimatedMinutes: 18,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk2-u1-l2',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    slug: 'hsk2-u1-l2-ongoing-actions',
    title: 'Hành động đang diễn ra với 正在',
    titleZh: '你在做什么呢',
    description: 'Học cách diễn đạt việc mình đang làm gì tại thời điểm nói.',
    objectives: [
      'Nắm vững cấu trúc 正在...呢',
      'Trả lời câu hỏi 你在做什么？',
      'Phủ định hành động đang tiếp diễn',
    ],
    estimatedMinutes: 20,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk2-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 3 =====================
  {
    id: 'lesson-hsk3-u1-l1',
    unitId: 'unit-hsk3-u1',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    slug: 'hsk3-u1-l1-travel-experience',
    title: 'Trải nghiệm du lịch & Trợ từ 过',
    titleZh: '你去过中国吗',
    description: 'Kể về trải nghiệm du lịch, những vùng đất đã từng ghé thăm và ẩm thực đã từng nếm thử.',
    objectives: [
      'Sử dụng trợ từ động thái 过 để nói về kinh nghiệm đã qua',
      'Hỏi thăm trải nghiệm của bạn bè',
      'Mô tả ấn tượng về chuyến du lịch',
    ],
    estimatedMinutes: 22,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 4 =====================
  {
    id: 'lesson-hsk4-u1-l1',
    unitId: 'unit-hsk4-u1',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    slug: 'hsk4-u1-l1-ba-sentence',
    title: 'Câu chữ 把 trong giao tiếp thực tế',
    titleZh: '把字句的应用',
    description: 'Thành thạo cấu trúc câu chữ 把 để diễn đạt hành động tác động làm thay đổi tân ngữ.',
    objectives: ['Hiểu bản chất ngữ pháp của câu chữ 把', 'Áp dụng vào tình huống dọn dẹp, sắp xếp công việc'],
    estimatedMinutes: 25,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 5 =====================
  {
    id: 'lesson-hsk5-u1-l1',
    unitId: 'unit-hsk5-u1',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    slug: 'hsk5-u1-l1-market-trend',
    title: 'Phân tích xu hướng kinh tế & công nghệ',
    titleZh: '科技发展与市场趋势',
    description: 'Đọc báo kinh tế, nhận định về xu hướng số hóa và cách mạng trí tuệ nhân tạo.',
    objectives: ['Nắm các thuật ngữ thương mại và công nghệ cao cấp', 'Trình bày quan điểm có dẫn chứng logic'],
    estimatedMinutes: 30,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 6 =====================
  {
    id: 'lesson-hsk6-u1-l1',
    unitId: 'unit-hsk6-u1',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    slug: 'hsk6-u1-l1-classical-idioms',
    title: 'Nghệ thuật thành ngữ & Triết lý ngôn từ',
    titleZh: '成语典故与修辞艺术',
    description: 'Phân tích chiều sâu điển cố của thành ngữ cổ và sắc thái biểu đạt văn chương tao nhã.',
    objectives: ['Hiểu ngữ cảnh văn hóa lịch sử của thành ngữ', 'Vận dụng chuẩn xác trong bài viết học thuật'],
    estimatedMinutes: 35,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];

// Mapping between lessons and vocabulary
export const LESSON_VOCABULARY_MAP: LessonVocabulary[] = [
  // Lesson 1 (Greetings)
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-003', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-004', order: 4, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-005', order: 5, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-006', order: 6, isCore: true },

  // Lesson 2 (How are you)
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: false },
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },

  // Lesson 3 (What is your name)
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-007', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-008', order: 2, isCore: true },

  // Lesson 4 (Nationality)
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-009', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-010', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-011', order: 3, isCore: true },

  // Lesson 5 (Eating & Drinking)
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-012', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-013', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-014', order: 3, isCore: true },

  // Lesson 6 (Shopping & Price)
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-015', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-016', order: 2, isCore: true },


  // HSK 1 Extension
  { lessonId: 'lesson-hsk1-u2-l7', vocabularyId: 'vocab-hsk1-017', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l7', vocabularyId: 'vocab-hsk1-018', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l7', vocabularyId: 'vocab-hsk1-019', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l7', vocabularyId: 'vocab-hsk1-020', order: 4, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l8', vocabularyId: 'vocab-hsk1-021', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l8', vocabularyId: 'vocab-hsk1-022', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l8', vocabularyId: 'vocab-hsk1-023', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l9', vocabularyId: 'vocab-hsk1-024', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l9', vocabularyId: 'vocab-hsk1-025', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l9', vocabularyId: 'vocab-hsk1-026', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l9', vocabularyId: 'vocab-hsk1-027', order: 4, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l9', vocabularyId: 'vocab-hsk1-028', order: 5, isCore: true },

  // HSK 2 Lesson 1
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-002', order: 2, isCore: true },

  // HSK 2 Lesson 2
  { lessonId: 'lesson-hsk2-u1-l2', vocabularyId: 'vocab-hsk2-003', order: 1, isCore: true },

  // HSK 3 Lesson 1
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-002', order: 2, isCore: true },

  // HSK 4 Lesson 1
  { lessonId: 'lesson-hsk4-u1-l1', vocabularyId: 'vocab-hsk4-001', order: 1, isCore: true },

  // HSK 5 Lesson 1
  { lessonId: 'lesson-hsk5-u1-l1', vocabularyId: 'vocab-hsk5-001', order: 1, isCore: true },

  // HSK 6 Lesson 1
  { lessonId: 'lesson-hsk6-u1-l1', vocabularyId: 'vocab-hsk6-001', order: 1, isCore: true },
];

export const LESSON_DIALOGUES: Record<string, DialogueLine[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'd1-1',
      speaker: 'Lina 老师',
      chinese: '你好！欢迎来到中文课堂。',
      pinyin: 'Nǐ hǎo! Huānyíng lái dào zhōngwén kètáng.',
      translationVi: 'Chào bạn! Chào mừng bạn đến với lớp học tiếng Trung.',
    },
    {
      id: 'd1-2',
      speaker: 'Học viên',
      chinese: '老师好！很高兴认识您。',
      pinyin: 'Lǎoshī hǎo! Hěn gāoxìng rènshi nín.',
      translationVi: 'Chào cô ạ! Rất vui được làm quen với cô.',
    },
    {
      id: 'd1-3',
      speaker: 'Lina 老师',
      chinese: '谢谢你，不客气。我们一起努力吧！',
      pinyin: 'Xièxie nǐ, bú kèqi. Wǒmen yìqǐ nǔlì ba!',
      translationVi: 'Cảm ơn em, đừng khách sáo. Chúng ta cùng cố gắng nhé!',
    },
    {
      id: 'd1-4',
      speaker: 'Học viên',
      chinese: '好的，老师再见！',
      pinyin: 'Hǎo de, lǎoshī zàijiàn!',
      translationVi: 'Vâng ạ, tạm biệt cô!',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'd2-1',
      speaker: 'Tiểu Minh',
      chinese: '你好，你好吗？',
      pinyin: 'Nǐ hǎo, nǐ hǎo ma?',
      translationVi: 'Chào bạn, bạn khỏe không?',
    },
    {
      id: 'd2-2',
      speaker: 'Học viên',
      chinese: '我很好，谢谢。你呢？',
      pinyin: 'Wǒ hěn hǎo, xièxie. Nǐ ne?',
      translationVi: 'Tôi rất khỏe, cảm ơn. Còn bạn thì sao?',
    },
    {
      id: 'd2-3',
      speaker: 'Tiểu Minh',
      chinese: '我也很好！',
      pinyin: 'Wǒ yě hěn hǎo!',
      translationVi: 'Tôi cũng rất khỏe!',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'd3-1',
      speaker: 'Lina 老师',
      chinese: '你好！请问你叫什么名字？',
      pinyin: 'Nǐ hǎo! Qǐngwèn nǐ jiào shénme míngzi?',
      translationVi: 'Chào bạn! Cho mình hỏi bạn tên là gì?',
    },
    {
      id: 'd3-2',
      speaker: 'Học viên',
      chinese: '我叫李明。你叫什么名字？',
      pinyin: 'Wǒ jiào Lǐ Míng. Nǐ jiào shénme míngzi?',
      translationVi: 'Tôi tên là Lý Minh. Bạn tên là gì?',
    },
    {
      id: 'd3-3',
      speaker: 'Lina 老师',
      chinese: '我叫Lina。认识你很高兴！',
      pinyin: 'Wǒ jiào Lina. Rènshi nǐ hěn gāoxìng!',
      translationVi: 'Tôi tên là Lina. Rất vui được biết bạn!',
    },
  ],

  'lesson-hsk1-u2-l7': [
    { id: 'd7-1', speaker: 'Lina 老师', chinese: '这是你的家吗？', pinyin: 'Zhè shì nǐ de jiā ma?', translationVi: 'Đây là nhà của bạn à?' },
    { id: 'd7-2', speaker: 'Học viên', chinese: '是，这是我的家。', pinyin: 'Shì, zhè shì wǒ de jiā.', translationVi: 'Đúng, đây là nhà của tôi.' },
    { id: 'd7-3', speaker: 'Lina 老师', chinese: '你爸爸妈妈好吗？', pinyin: 'Nǐ bàba māma hǎo ma?', translationVi: 'Bố mẹ bạn khỏe không?' },
    { id: 'd7-4', speaker: 'Học viên', chinese: '他们很好，谢谢！', pinyin: 'Tāmen hěn hǎo, xièxie!', translationVi: 'Họ rất khỏe, cảm ơn cô!' },
  ],
  'lesson-hsk1-u2-l8': [
    { id: 'd8-1', speaker: 'Tiểu Minh', chinese: '今天星期几？', pinyin: 'Jīntiān xīngqī jǐ?', translationVi: 'Hôm nay là thứ mấy?' },
    { id: 'd8-2', speaker: 'Học viên', chinese: '今天星期六。', pinyin: 'Jīntiān xīngqī liù.', translationVi: 'Hôm nay là thứ Bảy.' },
    { id: 'd8-3', speaker: 'Tiểu Minh', chinese: '明天一起喝茶吗？', pinyin: 'Míngtiān yìqǐ hē chá ma?', translationVi: 'Ngày mai cùng đi uống trà nhé?' },
    { id: 'd8-4', speaker: 'Học viên', chinese: '好啊，明天见！', pinyin: 'Hǎo a, míngtiān jiàn!', translationVi: 'Được chứ, hẹn gặp ngày mai!' },
  ],
  'lesson-hsk1-u3-l9': [
    { id: 'd9-1', speaker: 'Lina 老师', chinese: '周末你喜欢做什么？', pinyin: 'Zhōumò nǐ xǐhuan zuò shénme?', translationVi: 'Cuối tuần bạn thích làm gì?' },
    { id: 'd9-2', speaker: 'Học viên', chinese: '我喜欢看电影，也喜欢听音乐。', pinyin: 'Wǒ xǐhuan kàn diànyǐng, yě xǐhuan tīng yīnyuè.', translationVi: 'Tôi thích xem phim và cũng thích nghe nhạc.' },
    { id: 'd9-3', speaker: 'Lina 老师', chinese: '明天一起看电影吗？', pinyin: 'Míngtiān yìqǐ kàn diànyǐng ma?', translationVi: 'Ngày mai cùng xem phim nhé?' },
    { id: 'd9-4', speaker: 'Học viên', chinese: '好啊！', pinyin: 'Hǎo a!', translationVi: 'Được chứ!' },
  ],

};

export const LESSON_QUIZZES: Record<string, QuizQuestion[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'q-hsk1-l1-01',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 1,
      question: 'Khi chào một người lớn tuổi hoặc thầy cô một cách tôn trọng, ta dùng từ nào?',
      questionPinyin: 'Kính ngữ chào hỏi',
      options: [
        { id: 'opt-1', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-2', text: '您好 (Nín hǎo)', isCorrect: true },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '不客气 (Bú kèqi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '您 (nín) là đại từ tôn kính của 你 (nǐ), dùng để chào hỏi người lớn tuổi, khách hàng hoặc thầy cô.',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-02',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'translation',
      order: 2,
      question: 'Dịch câu sau sang tiếng Trung: "Cảm ơn bạn!"',
      questionPinyin: 'Xièxie nǐ!',
      options: [
        { id: 'opt-1', text: '对不起 (Duìbuqǐ)', isCorrect: false },
        { id: 'opt-2', text: '谢谢你 (Xièxie nǐ)', isCorrect: true },
        { id: 'opt-3', text: '不客气 (Bú kèqi)', isCorrect: false },
        { id: 'opt-4', text: '没关系 (Méi guānxi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '谢谢 (xièxie) nghĩa là cảm ơn. 谢谢你 nghĩa là cảm ơn bạn.',
      vocabularyIds: ['vocab-hsk1-004'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-03',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 3,
      question: 'Khi ai đó nói "谢谢你！", cách đáp lại lịch sự nhất là gì?',
      options: [
        { id: 'opt-1', text: '不客气 (Bú kèqi)', isCorrect: true },
        { id: 'opt-2', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '叫什么 (Jiào shénme)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '不客气 (Bú kèqi) nghĩa là không có chi, đừng khách sáo.',
      vocabularyIds: ['vocab-hsk1-005'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-04',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 4,
      question: 'Từ "再见" (zàijiàn) có nghĩa tương đương với từ nào trong tiếng Việt?',
      options: [
        { id: 'opt-1', text: 'Xin chào', isCorrect: false },
        { id: 'opt-2', text: 'Tạm biệt / Hẹn gặp lại', isCorrect: true },
        { id: 'opt-3', text: 'Xin lỗi', isCorrect: false },
        { id: 'opt-4', text: 'Làm phiền', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '再 (zài) là lại, 见 (jiàn) là gặp. 再见 nghĩa là hẹn gặp lại, tạm biệt.',
      vocabularyIds: ['vocab-hsk1-006'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-05',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'fill_blank',
      order: 5,
      question: 'Điền từ thích hợp vào chỗ trống: "老师，___ 好！"',
      questionPinyin: 'Lǎoshī, ___ hǎo!',
      options: [
        { id: 'opt-1', text: '您 (nín)', isCorrect: true },
        { id: 'opt-2', text: '谢 (xiè)', isCorrect: false },
        { id: 'opt-3', text: '见 (jiàn)', isCorrect: false },
        { id: 'opt-4', text: '气 (qì)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: 'Để bày tỏ sự tôn trọng với thầy cô giáo, ta dùng kính ngữ 您 (nín).',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'q-hsk1-l2-01',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'multiple_choice',
      order: 1,
      question: 'Để hỏi "Bạn khỏe không?", câu chuẩn xác là:',
      options: [
        { id: 'opt-1', text: '你好吗？(Nǐ hǎo ma?)', isCorrect: true },
        { id: 'opt-2', text: '你是谁？(Nǐ shì shéi?)', isCorrect: false },
        { id: 'opt-3', text: '你好！(Nǐ hǎo!)', isCorrect: false },
        { id: 'opt-4', text: '谢谢你。(Xièxie nǐ.)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '吗 đặt ở cuối câu trần thuật để tạo câu hỏi.',
      grammarPointIds: ['grammar-hsk1-002'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l2-02',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'translation',
      order: 2,
      question: 'Câu "我很好" có nghĩa là gì?',
      options: [
        { id: 'opt-1', text: 'Tôi không khỏe', isCorrect: false },
        { id: 'opt-2', text: 'Tôi rất khỏe / rất tốt', isCorrect: true },
        { id: 'opt-3', text: 'Tôi tên là Hảo', isCorrect: false },
        { id: 'opt-4', text: 'Tôi rất thích', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '很 (hěn) = rất, 好 (hǎo) = tốt, khỏe.',
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'q-hsk1-l3-01',
      lessonId: 'lesson-hsk1-u2-l3',
      type: 'multiple_choice',
      order: 1,
      question: 'Cụm từ "什么名字" (shénme míngzi) có nghĩa là:',
      options: [
        { id: 'opt-1', text: 'tên gì', isCorrect: true },
        { id: 'opt-2', text: 'người nào', isCorrect: false },
        { id: 'opt-3', text: 'ở đâu', isCorrect: false },
        { id: 'opt-4', text: 'bao nhiêu tuổi', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '什么 (shénme) = cái gì, 名字 (míngzi) = tên.',
      vocabularyIds: ['vocab-hsk1-007', 'vocab-hsk1-008'],
      points: 10,
      difficulty: 'easy',
    },
  ],

  'lesson-hsk1-u2-l7': [
    { id: 'q-hsk1-l7-01', lessonId: 'lesson-hsk1-u2-l7', type: 'multiple_choice', order: 1, question: 'Câu nào có nghĩa "Đây là nhà của tôi"?', options: [
      { id: 'opt-1', text: '这是我的家。', isCorrect: true }, { id: 'opt-2', text: '我喜欢喝茶。', isCorrect: false }, { id: 'opt-3', text: '今天星期几？', isCorrect: false }, { id: 'opt-4', text: '你叫什么名字？', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '我的 = của tôi, 家 = nhà/gia đình.', vocabularyIds: ['vocab-hsk1-019'], grammarPointIds: ['grammar-hsk1-005'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l7-02', lessonId: 'lesson-hsk1-u2-l7', type: 'translation', order: 2, question: 'Dịch: "Mẹ tôi rất khỏe."', options: [
      { id: 'opt-1', text: '我妈妈很好。', isCorrect: true }, { id: 'opt-2', text: '我爸爸很好。', isCorrect: false }, { id: 'opt-3', text: '我是学生。', isCorrect: false }, { id: 'opt-4', text: '我家很好。', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '我妈妈 = mẹ tôi; 很好 = rất khỏe/tốt.', vocabularyIds: ['vocab-hsk1-018'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l7-03', lessonId: 'lesson-hsk1-u2-l7', type: 'fill_blank', order: 3, question: 'Điền từ: 这是___爸爸。', options: [
      { id: 'opt-1', text: '我', isCorrect: false }, { id: 'opt-2', text: '我的', isCorrect: true }, { id: 'opt-3', text: '吗', isCorrect: false }, { id: 'opt-4', text: '什么', isCorrect: false },
    ], correctAnswer: 'opt-2', explanation: 'Mẫu sở hữu: 我 + 的 + 爸爸 → 我的爸爸.', grammarPointIds: ['grammar-hsk1-005'], points: 10, difficulty: 'easy' },
  ],
  'lesson-hsk1-u2-l8': [
    { id: 'q-hsk1-l8-01', lessonId: 'lesson-hsk1-u2-l8', type: 'multiple_choice', order: 1, question: 'Hỏi "Hôm nay là thứ mấy?" bằng câu nào?', options: [
      { id: 'opt-1', text: '今天星期几？', isCorrect: true }, { id: 'opt-2', text: '明天好吗？', isCorrect: false }, { id: 'opt-3', text: '你是哪国人？', isCorrect: false }, { id: 'opt-4', text: '你喜欢什么？', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '今天 = hôm nay, 星期几 = thứ mấy.', vocabularyIds: ['vocab-hsk1-021', 'vocab-hsk1-023'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l8-02', lessonId: 'lesson-hsk1-u2-l8', type: 'translation', order: 2, question: 'Dịch: "Ngày mai gặp lại."', options: [
      { id: 'opt-1', text: '明天见！', isCorrect: true }, { id: 'opt-2', text: '今天见！', isCorrect: false }, { id: 'opt-3', text: '明天好！', isCorrect: false }, { id: 'opt-4', text: '再见今天！', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '明天 = ngày mai, 见 = gặp.', vocabularyIds: ['vocab-hsk1-022'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l8-03', lessonId: 'lesson-hsk1-u2-l8', type: 'ordering', order: 3, question: 'Sắp xếp thành câu đúng: "Hôm nay là thứ Hai."', options: [
      { id: 'opt-1', text: '今天', isCorrect: true }, { id: 'opt-2', text: '星期一', isCorrect: true },
    ], correctAnswer: ['opt-1', 'opt-2'], explanation: 'Trật tự: 今天 + 星期一.', vocabularyIds: ['vocab-hsk1-021', 'vocab-hsk1-023'], points: 10, difficulty: 'easy' },
  ],
  'lesson-hsk1-u3-l9': [
    { id: 'q-hsk1-l9-01', lessonId: 'lesson-hsk1-u3-l9', type: 'multiple_choice', order: 1, question: 'Câu nào có nghĩa "Tôi thích xem phim"?', options: [
      { id: 'opt-1', text: '我喜欢看电影。', isCorrect: true }, { id: 'opt-2', text: '我喜欢喝茶。', isCorrect: false }, { id: 'opt-3', text: '我爸爸看电影。', isCorrect: false }, { id: 'opt-4', text: '我很好。', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '喜欢 + 看电影 diễn đạt sở thích xem phim.', vocabularyIds: ['vocab-hsk1-024', 'vocab-hsk1-025', 'vocab-hsk1-026'], grammarPointIds: ['grammar-hsk1-006'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l9-02', lessonId: 'lesson-hsk1-u3-l9', type: 'translation', order: 2, question: 'Dịch: "Tôi thích nghe nhạc."', options: [
      { id: 'opt-1', text: '我喜欢听音乐。', isCorrect: true }, { id: 'opt-2', text: '我喜欢看电影。', isCorrect: false }, { id: 'opt-3', text: '我想喝茶。', isCorrect: false }, { id: 'opt-4', text: '我听见音乐。', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: '喜欢 + 听音乐 = thích nghe nhạc.', vocabularyIds: ['vocab-hsk1-024', 'vocab-hsk1-027', 'vocab-hsk1-028'], grammarPointIds: ['grammar-hsk1-006'], points: 10, difficulty: 'easy' },
    { id: 'q-hsk1-l9-03', lessonId: 'lesson-hsk1-u3-l9', type: 'multiple_choice', order: 3, question: 'Chọn câu hỏi tự nhiên để hỏi sở thích:', options: [
      { id: 'opt-1', text: '你喜欢看电影吗？', isCorrect: true }, { id: 'opt-2', text: '你是看电影吗？', isCorrect: false }, { id: 'opt-3', text: '你叫什么电影？', isCorrect: false }, { id: 'opt-4', text: '你哪喜欢电影？', isCorrect: false },
    ], correctAnswer: 'opt-1', explanation: 'Câu trần thuật + 吗 tạo câu hỏi Có/Không.', grammarPointIds: ['grammar-hsk1-002', 'grammar-hsk1-006'], points: 10, difficulty: 'easy' },
  ],

};
