import {
  Lesson,
  LessonSection,
  QuizQuestion,
  LessonVocabulary,
  DialogueLine,
} from '../types/curriculum';

export const ALL_CURRICULUM_LESSONS: Lesson[] = [
  // ===================== HSK 1 =====================
  // Unit 1
  {
    id: 'lesson-hsk1-u1-l1',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    slug: 'hsk1-u1-l1-greetings',
    title: 'Chào hỏi cơ bản',
    titleZh: '问好与致谢',
    description: 'Học cách chào hỏi, cảm ơn và tạm biệt một cách tự nhiên, chuẩn mực và lịch sự.',
    objectives: [
      'Biết cách chào người khác bằng 你好 và kính ngữ 您好',
      'Nói lời cảm ơn (谢谢) và đáp lại khiêm tốn (不客气)',
      'Chào tạm biệt đối phương chuẩn xác (再见)',
    ],
    estimatedMinutes: 12,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u1-l2',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    slug: 'hsk1-u1-l2-how-are-you',
    title: 'Hỏi thăm sức khỏe & Đại từ nghi vấn 吗',
    titleZh: '身体好吗',
    description: 'Biết cách hỏi thăm sức khỏe người khác và sử dụng trợ từ nghi vấn 吗 để tạo câu hỏi.',
    objectives: [
      'Sử dụng cấu trúc 你好吗？ để hỏi thăm sức khỏe',
      'Trả lời bằng phó từ 很 (rất): 我很好 (Tôi rất khỏe)',
      'Nắm vững trợ từ nghi vấn 吗 ở cuối câu trần thuật',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 2
  {
    id: 'lesson-hsk1-u2-l3',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    slug: 'hsk1-u2-l3-what-is-your-name',
    title: 'Bạn tên là gì?',
    titleZh: '你叫什么名字',
    description: 'Làm quen với đại từ nghi vấn 什么 và mẫu câu hỏi tên họ trong tiếng Trung.',
    objectives: [
      'Hỏi tên người đối diện bằng 你叫什么名字？',
      'Tự tin giới thiệu họ tên bản thân bằng 我叫...',
      'Phân biệt cách xưng hô bạn bè và người lớn tuổi',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l2',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u2-l4',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 4,
    slug: 'hsk1-u2-l4-nationality',
    title: 'Quốc tịch & Câu phán đoán với 是',
    titleZh: '你是哪国人',
    description: 'Sử dụng động từ phán đoán 是 để giới thiệu quốc tịch, quê hương và xuất thân.',
    objectives: [
      'Hỏi quốc tịch người khác bằng 你是哪国人？',
      'Nói quốc tịch bản thân: 我是越南人 / 我是中国人',
      'Thành thạo cấu trúc phán đoán A 是 B',
    ],
    estimatedMinutes: 16,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l3',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 3
  {
    id: 'lesson-hsk1-u3-l5',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 5,
    slug: 'hsk1-u3-l5-eating-and-drinking',
    title: 'Ăn uống & Gọi món cơ bản',
    titleZh: '你想吃什么',
    description: 'Hỏi về sở thích ăn uống, mời người khác dùng trà và gọi món đơn giản.',
    objectives: [
      'Sử dụng động từ 吃 (ăn) và 喝 (uống)',
      'Hỏi người khác muốn ăn gì (你想吃什么？)',
      'Mời nước lịch sự (请喝茶)',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l4',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u3-l6',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 6,
    slug: 'hsk1-u3-l6-how-much-money',
    title: 'Hỏi giá tiền & Mua sắm',
    titleZh: '这个多少钱',
    description: 'Học cách hỏi giá cả hàng hóa, con số tiền tệ và hoàn tất thanh toán.',
    objectives: [
      'Hỏi giá bằng 這個多少錢？ (Cái này bao nhiêu tiền?)',
      'Hiểu đơn vị tiền tệ cơ bản (块 / 元)',
      'Thương lượng giá đơn giản khi đi chợ',
    ],
    estimatedMinutes: 18,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u3-l5',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 2 =====================
  {
    id: 'lesson-hsk2-u1-l1',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    slug: 'hsk2-u1-l1-daily-routine',
    title: 'Thói quen sinh hoạt mỗi ngày',
    titleZh: '我每天早上七点起床',
    description: 'Mô tả thói quen sinh hoạt hàng ngày, thức dậy, ăn sáng và tập thể dục.',
    objectives: [
      'Nói giờ chuẩn xác và sắp xếp thời gian biểu',
      'Sử dụng động từ ly hợp 起床 (thức dậy), 跑步 (chạy bộ)',
      'Miêu tả chuỗi hành động thường nhật',
    ],
    estimatedMinutes: 18,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk2-u1-l2',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    slug: 'hsk2-u1-l2-ongoing-actions',
    title: 'Hành động đang diễn ra với 正在',
    titleZh: '你在做什么呢',
    description: 'Học cách diễn đạt việc mình đang làm gì tại thời điểm nói.',
    objectives: [
      'Nắm vững cấu trúc 正在...呢',
      'Trả lời câu hỏi 你在做什么？',
      'Phủ định hành động đang tiếp diễn',
    ],
    estimatedMinutes: 20,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk2-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 3 =====================
  {
    id: 'lesson-hsk3-u1-l1',
    unitId: 'unit-hsk3-u1',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    slug: 'hsk3-u1-l1-travel-experience',
    title: 'Trải nghiệm du lịch & Trợ từ 过',
    titleZh: '你去过中国吗',
    description: 'Kể về trải nghiệm du lịch, những vùng đất đã từng ghé thăm và ẩm thực đã từng nếm thử.',
    objectives: [
      'Sử dụng trợ từ động thái 过 để nói về kinh nghiệm đã qua',
      'Hỏi thăm trải nghiệm của bạn bè',
      'Mô tả ấn tượng về chuyến du lịch',
    ],
    estimatedMinutes: 22,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 4 =====================
  {
    id: 'lesson-hsk4-u1-l1',
    unitId: 'unit-hsk4-u1',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    slug: 'hsk4-u1-l1-ba-sentence',
    title: 'Câu chữ 把 trong giao tiếp thực tế',
    titleZh: '把字句的应用',
    description: 'Thành thạo cấu trúc câu chữ 把 để diễn đạt hành động tác động làm thay đổi tân ngữ.',
    objectives: ['Hiểu bản chất ngữ pháp của câu chữ 把', 'Áp dụng vào tình huống dọn dẹp, sắp xếp công việc'],
    estimatedMinutes: 25,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 5 =====================
  {
    id: 'lesson-hsk5-u1-l1',
    unitId: 'unit-hsk5-u1',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    slug: 'hsk5-u1-l1-market-trend',
    title: 'Phân tích xu hướng kinh tế & công nghệ',
    titleZh: '科技发展与市场趋势',
    description: 'Đọc báo kinh tế, nhận định về xu hướng số hóa và cách mạng trí tuệ nhân tạo.',
    objectives: ['Nắm các thuật ngữ thương mại và công nghệ cao cấp', 'Trình bày quan điểm có dẫn chứng logic'],
    estimatedMinutes: 30,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 6 =====================
  {
    id: 'lesson-hsk6-u1-l1',
    unitId: 'unit-hsk6-u1',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    slug: 'hsk6-u1-l1-classical-idioms',
    title: 'Nghệ thuật thành ngữ & Triết lý ngôn từ',
    titleZh: '成语典故与修辞艺术',
    description: 'Phân tích chiều sâu điển cố của thành ngữ cổ và sắc thái biểu đạt văn chương tao nhã.',
    objectives: ['Hiểu ngữ cảnh văn hóa lịch sử của thành ngữ', 'Vận dụng chuẩn xác trong bài viết học thuật'],
    estimatedMinutes: 35,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];

// Mapping between lessons and vocabulary
export const LESSON_VOCABULARY_MAP: LessonVocabulary[] = [
  // Lesson 1 (Greetings)
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-003', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-004', order: 4, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-005', order: 5, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-006', order: 6, isCore: true },

  // Lesson 2 (How are you)
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: false },
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },

  // Lesson 3 (What is your name)
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-007', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-008', order: 2, isCore: true },

  // Lesson 4 (Nationality)
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-009', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-010', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-011', order: 3, isCore: true },

  // Lesson 5 (Eating & Drinking)
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-012', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-013', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-014', order: 3, isCore: true },

  // Lesson 6 (Shopping & Price)
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-015', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-016', order: 2, isCore: true },

  // HSK 2 Lesson 1
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-002', order: 2, isCore: true },

  // HSK 2 Lesson 2
  { lessonId: 'lesson-hsk2-u1-l2', vocabularyId: 'vocab-hsk2-003', order: 1, isCore: true },

  // HSK 3 Lesson 1
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-002', order: 2, isCore: true },

  // HSK 4 Lesson 1
  { lessonId: 'lesson-hsk4-u1-l1', vocabularyId: 'vocab-hsk4-001', order: 1, isCore: true },

  // HSK 5 Lesson 1
  { lessonId: 'lesson-hsk5-u1-l1', vocabularyId: 'vocab-hsk5-001', order: 1, isCore: true },

  // HSK 6 Lesson 1
  { lessonId: 'lesson-hsk6-u1-l1', vocabularyId: 'vocab-hsk6-001', order: 1, isCore: true },
];

export const LESSON_DIALOGUES: Record<string, DialogueLine[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'd1-1',
      speaker: 'Lina 老师',
      chinese: '你好！欢迎来到中文课堂。',
      pinyin: 'Nǐ hǎo! Huānyíng lái dào zhōngwén kètáng.',
      translationVi: 'Chào bạn! Chào mừng bạn đến với lớp học tiếng Trung.',
    },
    {
      id: 'd1-2',
      speaker: 'Học viên',
      chinese: '老师好！很高兴认识您。',
      pinyin: 'Lǎoshī hǎo! Hěn gāoxìng rènshi nín.',
      translationVi: 'Chào cô ạ! Rất vui được làm quen với cô.',
    },
    {
      id: 'd1-3',
      speaker: 'Lina 老师',
      chinese: '谢谢你，不客气。我们一起努力吧！',
      pinyin: 'Xièxie nǐ, bú kèqi. Wǒmen yìqǐ nǔlì ba!',
      translationVi: 'Cảm ơn em, đừng khách sáo. Chúng ta cùng cố gắng nhé!',
    },
    {
      id: 'd1-4',
      speaker: 'Học viên',
      chinese: '好的，老师再见！',
      pinyin: 'Hǎo de, lǎoshī zàijiàn!',
      translationVi: 'Vâng ạ, tạm biệt cô!',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'd2-1',
      speaker: 'Tiểu Minh',
      chinese: '你好，你好吗？',
      pinyin: 'Nǐ hǎo, nǐ hǎo ma?',
      translationVi: 'Chào bạn, bạn khỏe không?',
    },
    {
      id: 'd2-2',
      speaker: 'Học viên',
      chinese: '我很好，谢谢。你呢？',
      pinyin: 'Wǒ hěn hǎo, xièxie. Nǐ ne?',
      translationVi: 'Tôi rất khỏe, cảm ơn. Còn bạn thì sao?',
    },
    {
      id: 'd2-3',
      speaker: 'Tiểu Minh',
      chinese: '我也很好！',
      pinyin: 'Wǒ yě hěn hǎo!',
      translationVi: 'Tôi cũng rất khỏe!',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'd3-1',
      speaker: 'Lina 老师',
      chinese: '你好！请问你叫什么名字？',
      pinyin: 'Nǐ hǎo! Qǐngwèn nǐ jiào shénme míngzi?',
      translationVi: 'Chào bạn! Cho mình hỏi bạn tên là gì?',
    },
    {
      id: 'd3-2',
      speaker: 'Học viên',
      chinese: '我叫李明。你叫什么名字？',
      pinyin: 'Wǒ jiào Lǐ Míng. Nǐ jiào shénme míngzi?',
      translationVi: 'Tôi tên là Lý Minh. Bạn tên là gì?',
    },
    {
      id: 'd3-3',
      speaker: 'Lina 老师',
      chinese: '我叫Lina。认识你很高兴！',
      pinyin: 'Wǒ jiào Lina. Rènshi nǐ hěn gāoxìng!',
      translationVi: 'Tôi tên là Lina. Rất vui được biết bạn!',
    },
  ],
};

export const LESSON_QUIZZES: Record<string, QuizQuestion[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'q-hsk1-l1-01',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 1,
      question: 'Khi chào một người lớn tuổi hoặc thầy cô một cách tôn trọng, ta dùng từ nào?',
      questionPinyin: 'Kính ngữ chào hỏi',
      options: [
        { id: 'opt-1', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-2', text: '您好 (Nín hǎo)', isCorrect: true },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '不客气 (Bú kèqi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '您 (nín) là đại từ tôn kính của 你 (nǐ), dùng để chào hỏi người lớn tuổi, khách hàng hoặc thầy cô.',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-02',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'translation',
      order: 2,
      question: 'Dịch câu sau sang tiếng Trung: "Cảm ơn bạn!"',
      questionPinyin: 'Xièxie nǐ!',
      options: [
        { id: 'opt-1', text: '对不起 (Duìbuqǐ)', isCorrect: false },
        { id: 'opt-2', text: '谢谢你 (Xièxie nǐ)', isCorrect: true },
        { id: 'opt-3', text: '不客气 (Bú kèqi)', isCorrect: false },
        { id: 'opt-4', text: '没关系 (Méi guānxi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '谢谢 (xièxie) nghĩa là cảm ơn. 谢谢你 nghĩa là cảm ơn bạn.',
      vocabularyIds: ['vocab-hsk1-004'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-03',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 3,
      question: 'Khi ai đó nói "谢谢你！", cách đáp lại lịch sự nhất là gì?',
      options: [
        { id: 'opt-1', text: '不客气 (Bú kèqi)', isCorrect: true },
        { id: 'opt-2', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '叫什么 (Jiào shénme)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '不客气 (Bú kèqi) nghĩa là không có chi, đừng khách sáo.',
      vocabularyIds: ['vocab-hsk1-005'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-04',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 4,
      question: 'Từ "再见" (zàijiàn) có nghĩa tương đương với từ nào trong tiếng Việt?',
      options: [
        { id: 'opt-1', text: 'Xin chào', isCorrect: false },
        { id: 'opt-2', text: 'Tạm biệt / Hẹn gặp lại', isCorrect: true },
        { id: 'opt-3', text: 'Xin lỗi', isCorrect: false },
        { id: 'opt-4', text: 'Làm phiền', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '再 (zài) là lại, 见 (jiàn) là gặp. 再见 nghĩa là hẹn gặp lại, tạm biệt.',
      vocabularyIds: ['vocab-hsk1-006'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-05',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'fill_blank',
      order: 5,
      question: 'Điền từ thích hợp vào chỗ trống: "老师，___ 好！"',
      questionPinyin: 'Lǎoshī, ___ hǎo!',
      options: [
        { id: 'opt-1', text: '您 (nín)', isCorrect: true },
        { id: 'opt-2', text: '谢 (xiè)', isCorrect: false },
        { id: 'opt-3', text: '见 (jiàn)', isCorrect: false },
        { id: 'opt-4', text: '气 (qì)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: 'Để bày tỏ sự tôn trọng với thầy cô giáo, ta dùng kính ngữ 您 (nín).',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'q-hsk1-l2-01',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'multiple_choice',
      order: 1,
      question: 'Để hỏi "Bạn khỏe không?", câu chuẩn xác là:',
      options: [
        { id: 'opt-1', text: '你好吗？(Nǐ hǎo ma?)', isCorrect: true },
        { id: 'opt-2', text: '你是谁？(Nǐ shì shéi?)', isCorrect: false },
        { id: 'opt-3', text: '你好！(Nǐ hǎo!)', isCorrect: false },
        { id: 'opt-4', text: '谢谢你。(Xièxie nǐ.)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '吗 đặt ở cuối câu trần thuật để tạo câu hỏi.',
      grammarPointIds: ['grammar-hsk1-002'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l2-02',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'translation',
      order: 2,
      question: 'Câu "我很好" có nghĩa là gì?',
      options: [
        { id: 'opt-1', text: 'Tôi không khỏe', isCorrect: false },
        { id: 'opt-2', text: 'Tôi rất khỏe / rất tốt', isCorrect: true },
        { id: 'opt-3', text: 'Tôi tên là Hảo', isCorrect: false },
        { id: 'opt-4', text: 'Tôi rất thích', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '很 (hěn) = rất, 好 (hǎo) = tốt, khỏe.',
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'q-hsk1-l3-01',
      lessonId: 'lesson-hsk1-u2-l3',
      type: 'multiple_choice',
      order: 1,
      question: 'Cụm từ "什么名字" (shénme míngzi) có nghĩa là:',
      options: [
        { id: 'opt-1', text: 'tên gì', isCorrect: true },
        { id: 'opt-2', text: 'người nào', isCorrect: false },
        { id: 'opt-3', text: 'ở đâu', isCorrect: false },
        { id: 'opt-4', text: 'bao nhiêu tuổi', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '什么 (shénme) = cái gì, 名字 (míngzi) = tên.',
      vocabularyIds: ['vocab-hsk1-007', 'vocab-hsk1-008'],
      points: 10,
      difficulty: 'easy',
    },
  ],
};
