import {
  Lesson,
  LessonSection,
  QuizQuestion,
  LessonVocabulary,
  DialogueLine,
} from '../types/curriculum';

export const ALL_CURRICULUM_LESSONS: Lesson[] = [
  // ===================== HSK 1 =====================
  // Unit 1
  {
    id: 'lesson-hsk1-u1-l1',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 1,
    slug: 'hsk1-u1-l1-greetings',
    title: 'Chào hỏi cơ bản',
    titleZh: '问好与致谢',
    description: 'Học cách chào hỏi, cảm ơn và tạm biệt một cách tự nhiên, chuẩn mực và lịch sự.',
    objectives: [
      'Biết cách chào người khác bằng 你好 và kính ngữ 您好',
      'Nói lời cảm ơn (谢谢) và đáp lại khiêm tốn (不客气)',
      'Chào tạm biệt đối phương chuẩn xác (再见)',
    ],
    estimatedMinutes: 12,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u1-l2',
    unitId: 'unit-hsk1-u1',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 2,
    slug: 'hsk1-u1-l2-how-are-you',
    title: 'Hỏi thăm sức khỏe & Đại từ nghi vấn 吗',
    titleZh: '身体好吗',
    description: 'Biết cách hỏi thăm sức khỏe người khác và sử dụng trợ từ nghi vấn 吗 để tạo câu hỏi.',
    objectives: [
      'Sử dụng cấu trúc 你好吗？ để hỏi thăm sức khỏe',
      'Trả lời bằng phó từ 很 (rất): 我很好 (Tôi rất khỏe)',
      'Nắm vững trợ từ nghi vấn 吗 ở cuối câu trần thuật',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 2
  {
    id: 'lesson-hsk1-u2-l3',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 3,
    slug: 'hsk1-u2-l3-what-is-your-name',
    title: 'Bạn tên là gì?',
    titleZh: '你叫什么名字',
    description: 'Làm quen với đại từ nghi vấn 什么 và mẫu câu hỏi tên họ trong tiếng Trung.',
    objectives: [
      'Hỏi tên người đối diện bằng 你叫什么名字？',
      'Tự tin giới thiệu họ tên bản thân bằng 我叫...',
      'Phân biệt cách xưng hô bạn bè và người lớn tuổi',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u1-l2',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u2-l4',
    unitId: 'unit-hsk1-u2',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 4,
    slug: 'hsk1-u2-l4-nationality',
    title: 'Quốc tịch & Câu phán đoán với 是',
    titleZh: '你是哪国人',
    description: 'Sử dụng động từ phán đoán 是 để giới thiệu quốc tịch, quê hương và xuất thân.',
    objectives: [
      'Hỏi quốc tịch người khác bằng 你是哪国人？',
      'Nói quốc tịch bản thân: 我是越南人 / 我是中国人',
      'Thành thạo cấu trúc phán đoán A 是 B',
    ],
    estimatedMinutes: 16,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l3',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // Unit 3
  {
    id: 'lesson-hsk1-u3-l5',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 5,
    slug: 'hsk1-u3-l5-eating-and-drinking',
    title: 'Ăn uống & Gọi món cơ bản',
    titleZh: '你想吃什么',
    description: 'Hỏi về sở thích ăn uống, mời người khác dùng trà và gọi món đơn giản.',
    objectives: [
      'Sử dụng động từ 吃 (ăn) và 喝 (uống)',
      'Hỏi người khác muốn ăn gì (你想吃什么？)',
      'Mời nước lịch sự (请喝茶)',
    ],
    estimatedMinutes: 15,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u2-l4',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk1-u3-l6',
    unitId: 'unit-hsk1-u3',
    levelId: 'hsk-level-1',
    levelNumber: 1,
    order: 6,
    slug: 'hsk1-u3-l6-how-much-money',
    title: 'Hỏi giá tiền & Mua sắm',
    titleZh: '这个多少钱',
    description: 'Học cách hỏi giá cả hàng hóa, con số tiền tệ và hoàn tất thanh toán.',
    objectives: [
      'Hỏi giá bằng 這個多少錢？ (Cái này bao nhiêu tiền?)',
      'Hiểu đơn vị tiền tệ cơ bản (块 / 元)',
      'Thương lượng giá đơn giản khi đi chợ',
    ],
    estimatedMinutes: 18,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk1-u3-l5',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 2 =====================
  {
    id: 'lesson-hsk2-u1-l1',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 1,
    slug: 'hsk2-u1-l1-daily-routine',
    title: 'Thói quen sinh hoạt mỗi ngày',
    titleZh: '我每天早上七点起床',
    description: 'Mô tả thói quen sinh hoạt hàng ngày, thức dậy, ăn sáng và tập thể dục.',
    objectives: [
      'Nói giờ chuẩn xác và sắp xếp thời gian biểu',
      'Sử dụng động từ ly hợp 起床 (thức dậy), 跑步 (chạy bộ)',
      'Miêu tả chuỗi hành động thường nhật',
    ],
    estimatedMinutes: 18,
    difficulty: 'easy',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'lesson-hsk2-u1-l2',
    unitId: 'unit-hsk2-u1',
    levelId: 'hsk-level-2',
    levelNumber: 2,
    order: 2,
    slug: 'hsk2-u1-l2-ongoing-actions',
    title: 'Hành động đang diễn ra với 正在',
    titleZh: '你在做什么呢',
    description: 'Học cách diễn đạt việc mình đang làm gì tại thời điểm nói.',
    objectives: [
      'Nắm vững cấu trúc 正在...呢',
      'Trả lời câu hỏi 你在做什么？',
      'Phủ định hành động đang tiếp diễn',
    ],
    estimatedMinutes: 20,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk2-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 3 =====================
  {
    id: 'lesson-hsk3-u1-l1',
    unitId: 'unit-hsk3-u1',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 1,
    slug: 'hsk3-u1-l1-travel-experience',
    title: 'Trải nghiệm du lịch & Trợ từ 过',
    titleZh: '你去过中国吗',
    description: 'Kể về trải nghiệm du lịch, những vùng đất đã từng ghé thăm và ẩm thực đã từng nếm thử.',
    objectives: [
      'Sử dụng trợ từ động thái 过 để nói về kinh nghiệm đã qua',
      'Hỏi thăm trải nghiệm của bạn bè',
      'Mô tả ấn tượng về chuyến du lịch',
    ],
    estimatedMinutes: 22,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 4 =====================
  {
    id: 'lesson-hsk4-u1-l1',
    unitId: 'unit-hsk4-u1',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 1,
    slug: 'hsk4-u1-l1-ba-sentence',
    title: 'Câu chữ 把 trong giao tiếp thực tế',
    titleZh: '把字句的应用',
    description: 'Thành thạo cấu trúc câu chữ 把 để diễn đạt hành động tác động làm thay đổi tân ngữ.',
    objectives: ['Hiểu bản chất ngữ pháp của câu chữ 把', 'Áp dụng vào tình huống dọn dẹp, sắp xếp công việc'],
    estimatedMinutes: 25,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 5 =====================
  {
    id: 'lesson-hsk5-u1-l1',
    unitId: 'unit-hsk5-u1',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 1,
    slug: 'hsk5-u1-l1-market-trend',
    title: 'Phân tích xu hướng kinh tế & công nghệ',
    titleZh: '科技发展与市场趋势',
    description: 'Đọc báo kinh tế, nhận định về xu hướng số hóa và cách mạng trí tuệ nhân tạo.',
    objectives: ['Nắm các thuật ngữ thương mại và công nghệ cao cấp', 'Trình bày quan điểm có dẫn chứng logic'],
    estimatedMinutes: 30,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== HSK 6 =====================
  {
    id: 'lesson-hsk6-u1-l1',
    unitId: 'unit-hsk6-u1',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 1,
    slug: 'hsk6-u1-l1-classical-idioms',
    title: 'Nghệ thuật thành ngữ & Triết lý ngôn từ',
    titleZh: '成语典故与修辞艺术',
    description: 'Phân tích chiều sâu điển cố của thành ngữ cổ và sắc thái biểu đạt văn chương tao nhã.',
    objectives: ['Hiểu ngữ cảnh văn hóa lịch sử của thành ngữ', 'Vận dụng chuẩn xác trong bài viết học thuật'],
    estimatedMinutes: 35,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: null,
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // ===================== EXPANDED HSK 3–6 =====================
  {
    id: 'lesson-hsk3-u1-l2',
    unitId: 'unit-hsk3-u1',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 2,
    slug: 'hsk3-u1-l2-hotel-booking',
    title: 'Đặt phòng & Xử lý tình huống du lịch',
    titleZh: '预订酒店与旅行安排',
    description: 'Luyện hội thoại đặt phòng, hỏi tiện nghi và xử lý thay đổi lịch trình khi đi du lịch.',
    objectives: ['Đặt phòng bằng tiếng Trung', 'Hỏi tiện nghi và thời gian nhận phòng', 'Giải thích thay đổi lịch trình lịch sự'],
    estimatedMinutes: 24,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk3-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  {
    id: 'lesson-hsk3-u2-l3',
    unitId: 'unit-hsk3-u2',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 3,
    slug: 'hsk3-u2-l3-job-interview',
    title: 'Phỏng vấn & Kinh nghiệm làm việc',
    titleZh: '面试与工作经验',
    description: 'Thực hành giới thiệu kinh nghiệm, kỹ năng và mục tiêu nghề nghiệp trong một cuộc phỏng vấn.',
    objectives: ['Giới thiệu kinh nghiệm làm việc', 'Mô tả kỹ năng bằng câu phức', 'Trả lời câu hỏi phỏng vấn tự nhiên'],
    estimatedMinutes: 26,
    difficulty: 'medium',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk3-u1-l2',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  {
    id: 'lesson-hsk3-u2-l4',
    unitId: 'unit-hsk3-u2',
    levelId: 'hsk-level-3',
    levelNumber: 3,
    order: 4,
    slug: 'hsk3-u2-l4-work-study-plans',
    title: 'Kế hoạch học tập & Công việc',
    titleZh: '学习与工作计划',
    description: 'Nói về mục tiêu, kế hoạch và lý do lựa chọn một hướng học tập hoặc công việc.',
    objectives: ['Nêu mục tiêu rõ ràng', 'Giải thích nguyên nhân và kết quả', 'Thảo luận kế hoạch ngắn hạn'],
    estimatedMinutes: 25,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk3-u2-l3',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  {
    id: 'lesson-hsk4-u1-l2',
    unitId: 'unit-hsk4-u1',
    levelId: 'hsk-level-4',
    levelNumber: 4,
    order: 2,
    slug: 'hsk4-u1-l2-social-opinions',
    title: 'Quan điểm xã hội & Tranh luận nhẹ nhàng',
    titleZh: '社会观点与理性表达',
    description: 'Luyện trình bày quan điểm, đưa lý do và phản hồi ý kiến khác trong các chủ đề xã hội.',
    objectives: ['Trình bày quan điểm có dẫn chứng', 'Dùng liên từ để nối lập luận', 'Phản hồi ý kiến khác lịch sự'],
    estimatedMinutes: 30,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk4-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  {
    id: 'lesson-hsk5-u1-l2',
    unitId: 'unit-hsk5-u1',
    levelId: 'hsk-level-5',
    levelNumber: 5,
    order: 2,
    slug: 'hsk5-u1-l2-media-and-analysis',
    title: 'Đọc tin & Phân tích lập luận',
    titleZh: '新闻阅读与观点分析',
    description: 'Đọc một đoạn tin ngắn, xác định luận điểm và diễn đạt nhận xét bằng ngôn ngữ trang trọng.',
    objectives: ['Tóm tắt thông tin chính', 'Phân biệt dữ kiện và nhận định', 'Diễn đạt ý kiến theo văn phong trang trọng'],
    estimatedMinutes: 34,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk5-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },
  {
    id: 'lesson-hsk6-u1-l2',
    unitId: 'unit-hsk6-u1',
    levelId: 'hsk-level-6',
    levelNumber: 6,
    order: 2,
    slug: 'hsk6-u1-l2-idioms-in-context',
    title: 'Thành ngữ trong ngữ cảnh & Văn phong tinh tế',
    titleZh: '成语运用与语言风格',
    description: 'Phân tích thành ngữ theo ngữ cảnh và lựa chọn cách diễn đạt phù hợp với văn viết, văn nói.',
    objectives: ['Hiểu thành ngữ theo ngữ cảnh', 'Phân biệt sắc thái văn phong', 'Viết câu diễn đạt tự nhiên và chính xác'],
    estimatedMinutes: 38,
    difficulty: 'hard',
    status: 'published',
    isPublished: true,
    isRequired: true,
    prerequisiteLessonId: 'lesson-hsk6-u1-l1',
    completionRule: 'all_required_and_quiz',
    passingScore: 80,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-27T00:00:00Z',
  },

];

// Mapping between lessons and vocabulary
export const LESSON_VOCABULARY_MAP: LessonVocabulary[] = [
  // Lesson 1 (Greetings)
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-003', order: 3, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-004', order: 4, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-005', order: 5, isCore: true },
  { lessonId: 'lesson-hsk1-u1-l1', vocabularyId: 'vocab-hsk1-006', order: 6, isCore: true },

  // Lesson 2 (How are you)
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-001', order: 1, isCore: false },
  { lessonId: 'lesson-hsk1-u1-l2', vocabularyId: 'vocab-hsk1-002', order: 2, isCore: true },

  // Lesson 3 (What is your name)
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-007', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l3', vocabularyId: 'vocab-hsk1-008', order: 2, isCore: true },

  // Lesson 4 (Nationality)
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-009', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-010', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u2-l4', vocabularyId: 'vocab-hsk1-011', order: 3, isCore: true },

  // Lesson 5 (Eating & Drinking)
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-012', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-013', order: 2, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l5', vocabularyId: 'vocab-hsk1-014', order: 3, isCore: true },

  // Lesson 6 (Shopping & Price)
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-015', order: 1, isCore: true },
  { lessonId: 'lesson-hsk1-u3-l6', vocabularyId: 'vocab-hsk1-016', order: 2, isCore: true },

  // HSK 2 Lesson 1
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk2-u1-l1', vocabularyId: 'vocab-hsk2-002', order: 2, isCore: true },

  // HSK 2 Lesson 2
  { lessonId: 'lesson-hsk2-u1-l2', vocabularyId: 'vocab-hsk2-003', order: 1, isCore: true },

  // HSK 3 Lesson 1
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-001', order: 1, isCore: true },
  { lessonId: 'lesson-hsk3-u1-l1', vocabularyId: 'vocab-hsk3-002', order: 2, isCore: true },

  // HSK 4 Lesson 1
  { lessonId: 'lesson-hsk4-u1-l1', vocabularyId: 'vocab-hsk4-001', order: 1, isCore: true },

  // HSK 5 Lesson 1
  { lessonId: 'lesson-hsk5-u1-l1', vocabularyId: 'vocab-hsk5-001', order: 1, isCore: true },

  // HSK 6 Lesson 1
  { lessonId: 'lesson-hsk6-u1-l1', vocabularyId: 'vocab-hsk6-001', order: 1, isCore: true },
];

export const LESSON_DIALOGUES: Record<string, DialogueLine[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'd1-1',
      speaker: 'Lina 老师',
      chinese: '你好！欢迎来到中文课堂。',
      pinyin: 'Nǐ hǎo! Huānyíng lái dào zhōngwén kètáng.',
      translationVi: 'Chào bạn! Chào mừng bạn đến với lớp học tiếng Trung.',
    },
    {
      id: 'd1-2',
      speaker: 'Học viên',
      chinese: '老师好！很高兴认识您。',
      pinyin: 'Lǎoshī hǎo! Hěn gāoxìng rènshi nín.',
      translationVi: 'Chào cô ạ! Rất vui được làm quen với cô.',
    },
    {
      id: 'd1-3',
      speaker: 'Lina 老师',
      chinese: '谢谢你，不客气。我们一起努力吧！',
      pinyin: 'Xièxie nǐ, bú kèqi. Wǒmen yìqǐ nǔlì ba!',
      translationVi: 'Cảm ơn em, đừng khách sáo. Chúng ta cùng cố gắng nhé!',
    },
    {
      id: 'd1-4',
      speaker: 'Học viên',
      chinese: '好的，老师再见！',
      pinyin: 'Hǎo de, lǎoshī zàijiàn!',
      translationVi: 'Vâng ạ, tạm biệt cô!',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'd2-1',
      speaker: 'Tiểu Minh',
      chinese: '你好，你好吗？',
      pinyin: 'Nǐ hǎo, nǐ hǎo ma?',
      translationVi: 'Chào bạn, bạn khỏe không?',
    },
    {
      id: 'd2-2',
      speaker: 'Học viên',
      chinese: '我很好，谢谢。你呢？',
      pinyin: 'Wǒ hěn hǎo, xièxie. Nǐ ne?',
      translationVi: 'Tôi rất khỏe, cảm ơn. Còn bạn thì sao?',
    },
    {
      id: 'd2-3',
      speaker: 'Tiểu Minh',
      chinese: '我也很好！',
      pinyin: 'Wǒ yě hěn hǎo!',
      translationVi: 'Tôi cũng rất khỏe!',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'd3-1',
      speaker: 'Lina 老师',
      chinese: '你好！请问你叫什么名字？',
      pinyin: 'Nǐ hǎo! Qǐngwèn nǐ jiào shénme míngzi?',
      translationVi: 'Chào bạn! Cho mình hỏi bạn tên là gì?',
    },
    {
      id: 'd3-2',
      speaker: 'Học viên',
      chinese: '我叫李明。你叫什么名字？',
      pinyin: 'Wǒ jiào Lǐ Míng. Nǐ jiào shénme míngzi?',
      translationVi: 'Tôi tên là Lý Minh. Bạn tên là gì?',
    },
    {
      id: 'd3-3',
      speaker: 'Lina 老师',
      chinese: '我叫Lina。认识你很高兴！',
      pinyin: 'Wǒ jiào Lina. Rènshi nǐ hěn gāoxìng!',
      translationVi: 'Tôi tên là Lina. Rất vui được biết bạn!',
    },
  ],

  'lesson-hsk3-u1-l2': [
    { id: 'd-hsk3-l2-1', speaker: 'Nhân viên', chinese: '您好，请问您预订了几晚？', pinyin: 'Nín hǎo, qǐngwèn nín yùdìng le jǐ wǎn?', translationVi: 'Xin chào, bạn đặt phòng mấy đêm ạ?' },
    { id: 'd-hsk3-l2-2', speaker: 'Học viên', chinese: '我预订了三晚，想要一个安静的房间。', pinyin: 'Wǒ yùdìng le sān wǎn, xiǎng yào yí ge ānjìng de fángjiān.', translationVi: 'Tôi đặt ba đêm và muốn một phòng yên tĩnh.' },
    { id: 'd-hsk3-l2-3', speaker: 'Nhân viên', chinese: '没问题，早餐从七点开始。', pinyin: 'Méi wèntí, zǎocān cóng qī diǎn kāishǐ.', translationVi: 'Không vấn đề, bữa sáng bắt đầu từ bảy giờ.' },
  ],
  'lesson-hsk3-u2-l3': [
    { id: 'd-hsk3-l3-1', speaker: '面试官', chinese: '请介绍一下您的工作经验。', pinyin: 'Qǐng jièshào yíxià nín de gōngzuò jīngyàn.', translationVi: 'Hãy giới thiệu một chút về kinh nghiệm làm việc của bạn.' },
    { id: 'd-hsk3-l3-2', speaker: 'Học viên', chinese: '我以前在一家科技公司工作了两年。', pinyin: 'Wǒ yǐqián zài yì jiā kējì gōngsī gōngzuò le liǎng nián.', translationVi: 'Trước đây tôi đã làm việc hai năm tại một công ty công nghệ.' },
    { id: 'd-hsk3-l3-3', speaker: '面试官', chinese: '你为什么想换工作？', pinyin: 'Nǐ wèishénme xiǎng huàn gōngzuò?', translationVi: 'Vì sao bạn muốn đổi việc?' },
  ],
  'lesson-hsk3-u2-l4': [
    { id: 'd-hsk3-l4-1', speaker: 'Lina 老师', chinese: '你今年有什么学习计划？', pinyin: 'Nǐ jīnnián yǒu shénme xuéxí jìhuà?', translationVi: 'Năm nay bạn có kế hoạch học tập gì?' },
    { id: 'd-hsk3-l4-2', speaker: 'Học viên', chinese: '我打算提高口语，因为以后要和中国客户交流。', pinyin: 'Wǒ dǎsuàn tígāo kǒuyǔ, yīnwèi yǐhòu yào hé Zhōngguó kèhù jiāoliú.', translationVi: 'Tôi định nâng cao khẩu ngữ vì sau này cần giao tiếp với khách hàng Trung Quốc.' },
    { id: 'd-hsk3-l4-3', speaker: 'Lina 老师', chinese: '这个目标很清楚，也很实际。', pinyin: 'Zhège mùbiāo hěn qīngchu, yě hěn shíjì.', translationVi: 'Mục tiêu này rất rõ ràng và thực tế.' },
  ],
  'lesson-hsk4-u1-l2': [
    { id: 'd-hsk4-l2-1', speaker: '同事', chinese: '你怎么看现在的远程工作？', pinyin: 'Nǐ zěnme kàn xiànzài de yuǎnchéng gōngzuò?', translationVi: 'Bạn nghĩ thế nào về làm việc từ xa hiện nay?' },
    { id: 'd-hsk4-l2-2', speaker: 'Học viên', chinese: '我认为它提高了效率，但是也需要更好的沟通。', pinyin: 'Wǒ rènwéi tā tígāo le xiàolǜ, dànshì yě xūyào gèng hǎo de gōutōng.', translationVi: 'Tôi cho rằng nó tăng hiệu quả, nhưng cũng cần giao tiếp tốt hơn.' },
    { id: 'd-hsk4-l2-3', speaker: '同事', chinese: '你的理由很有道理。', pinyin: 'Nǐ de lǐyóu hěn yǒu dàolǐ.', translationVi: 'Lý do của bạn rất có lý.' },
  ],
  'lesson-hsk5-u1-l2': [
    { id: 'd-hsk5-l2-1', speaker: 'Lina 老师', chinese: '这篇报道主要讨论什么问题？', pinyin: 'Zhè piān bàodào zhǔyào tǎolùn shénme wèntí?', translationVi: 'Bài báo này chủ yếu thảo luận vấn đề gì?' },
    { id: 'd-hsk5-l2-2', speaker: 'Học viên', chinese: '文章分析了人工智能对就业市场的影响。', pinyin: 'Wénzhāng fēnxī le réngōng zhìnéng duì jiùyè shìchǎng de yǐngxiǎng.', translationVi: 'Bài viết phân tích ảnh hưởng của AI đến thị trường việc làm.' },
    { id: 'd-hsk5-l2-3', speaker: 'Lina 老师', chinese: '请你用一句话概括作者的观点。', pinyin: 'Qǐng nǐ yòng yí jù huà gàikuò zuòzhě de guāndiǎn.', translationVi: 'Hãy dùng một câu để tóm tắt quan điểm của tác giả.' },
  ],
  'lesson-hsk6-u1-l2': [
    { id: 'd-hsk6-l2-1', speaker: 'Lina 老师', chinese: '这个成语在这里表达什么含义？', pinyin: 'Zhège chéngyǔ zài zhèlǐ biǎodá shénme hányì?', translationVi: 'Thành ngữ này ở đây diễn đạt ý nghĩa gì?' },
    { id: 'd-hsk6-l2-2', speaker: 'Học viên', chinese: '它强调做事情不能只看眼前，还要考虑长远。', pinyin: 'Tā qiángdiào zuò shìqing bùnéng zhǐ kàn yǎnqián, hái yào kǎolǜ chángyuǎn.', translationVi: 'Nó nhấn mạnh rằng làm việc không thể chỉ nhìn trước mắt mà còn phải tính lâu dài.' },
    { id: 'd-hsk6-l2-3', speaker: 'Lina 老师', chinese: '很好，你注意到了语言的深层含义。', pinyin: 'Hěn hǎo, nǐ zhùyì dào le yǔyán de shēncéng hányì.', translationVi: 'Rất tốt, bạn đã chú ý đến tầng nghĩa sâu của ngôn ngữ.' },
  ],

};

export const LESSON_QUIZZES: Record<string, QuizQuestion[]> = {
  'lesson-hsk1-u1-l1': [
    {
      id: 'q-hsk1-l1-01',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 1,
      question: 'Khi chào một người lớn tuổi hoặc thầy cô một cách tôn trọng, ta dùng từ nào?',
      questionPinyin: 'Kính ngữ chào hỏi',
      options: [
        { id: 'opt-1', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-2', text: '您好 (Nín hǎo)', isCorrect: true },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '不客气 (Bú kèqi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '您 (nín) là đại từ tôn kính của 你 (nǐ), dùng để chào hỏi người lớn tuổi, khách hàng hoặc thầy cô.',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-02',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'translation',
      order: 2,
      question: 'Dịch câu sau sang tiếng Trung: "Cảm ơn bạn!"',
      questionPinyin: 'Xièxie nǐ!',
      options: [
        { id: 'opt-1', text: '对不起 (Duìbuqǐ)', isCorrect: false },
        { id: 'opt-2', text: '谢谢你 (Xièxie nǐ)', isCorrect: true },
        { id: 'opt-3', text: '不客气 (Bú kèqi)', isCorrect: false },
        { id: 'opt-4', text: '没关系 (Méi guānxi)', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '谢谢 (xièxie) nghĩa là cảm ơn. 谢谢你 nghĩa là cảm ơn bạn.',
      vocabularyIds: ['vocab-hsk1-004'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-03',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 3,
      question: 'Khi ai đó nói "谢谢你！", cách đáp lại lịch sự nhất là gì?',
      options: [
        { id: 'opt-1', text: '不客气 (Bú kèqi)', isCorrect: true },
        { id: 'opt-2', text: '你好 (Nǐ hǎo)', isCorrect: false },
        { id: 'opt-3', text: '再见 (Zàijiàn)', isCorrect: false },
        { id: 'opt-4', text: '叫什么 (Jiào shénme)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '不客气 (Bú kèqi) nghĩa là không có chi, đừng khách sáo.',
      vocabularyIds: ['vocab-hsk1-005'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-04',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'multiple_choice',
      order: 4,
      question: 'Từ "再见" (zàijiàn) có nghĩa tương đương với từ nào trong tiếng Việt?',
      options: [
        { id: 'opt-1', text: 'Xin chào', isCorrect: false },
        { id: 'opt-2', text: 'Tạm biệt / Hẹn gặp lại', isCorrect: true },
        { id: 'opt-3', text: 'Xin lỗi', isCorrect: false },
        { id: 'opt-4', text: 'Làm phiền', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '再 (zài) là lại, 见 (jiàn) là gặp. 再见 nghĩa là hẹn gặp lại, tạm biệt.',
      vocabularyIds: ['vocab-hsk1-006'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l1-05',
      lessonId: 'lesson-hsk1-u1-l1',
      type: 'fill_blank',
      order: 5,
      question: 'Điền từ thích hợp vào chỗ trống: "老师，___ 好！"',
      questionPinyin: 'Lǎoshī, ___ hǎo!',
      options: [
        { id: 'opt-1', text: '您 (nín)', isCorrect: true },
        { id: 'opt-2', text: '谢 (xiè)', isCorrect: false },
        { id: 'opt-3', text: '见 (jiàn)', isCorrect: false },
        { id: 'opt-4', text: '气 (qì)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: 'Để bày tỏ sự tôn trọng với thầy cô giáo, ta dùng kính ngữ 您 (nín).',
      vocabularyIds: ['vocab-hsk1-003'],
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u1-l2': [
    {
      id: 'q-hsk1-l2-01',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'multiple_choice',
      order: 1,
      question: 'Để hỏi "Bạn khỏe không?", câu chuẩn xác là:',
      options: [
        { id: 'opt-1', text: '你好吗？(Nǐ hǎo ma?)', isCorrect: true },
        { id: 'opt-2', text: '你是谁？(Nǐ shì shéi?)', isCorrect: false },
        { id: 'opt-3', text: '你好！(Nǐ hǎo!)', isCorrect: false },
        { id: 'opt-4', text: '谢谢你。(Xièxie nǐ.)', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '吗 đặt ở cuối câu trần thuật để tạo câu hỏi.',
      grammarPointIds: ['grammar-hsk1-002'],
      points: 10,
      difficulty: 'easy',
    },
    {
      id: 'q-hsk1-l2-02',
      lessonId: 'lesson-hsk1-u1-l2',
      type: 'translation',
      order: 2,
      question: 'Câu "我很好" có nghĩa là gì?',
      options: [
        { id: 'opt-1', text: 'Tôi không khỏe', isCorrect: false },
        { id: 'opt-2', text: 'Tôi rất khỏe / rất tốt', isCorrect: true },
        { id: 'opt-3', text: 'Tôi tên là Hảo', isCorrect: false },
        { id: 'opt-4', text: 'Tôi rất thích', isCorrect: false },
      ],
      correctAnswer: 'opt-2',
      explanation: '很 (hěn) = rất, 好 (hǎo) = tốt, khỏe.',
      points: 10,
      difficulty: 'easy',
    },
  ],
  'lesson-hsk1-u2-l3': [
    {
      id: 'q-hsk1-l3-01',
      lessonId: 'lesson-hsk1-u2-l3',
      type: 'multiple_choice',
      order: 1,
      question: 'Cụm từ "什么名字" (shénme míngzi) có nghĩa là:',
      options: [
        { id: 'opt-1', text: 'tên gì', isCorrect: true },
        { id: 'opt-2', text: 'người nào', isCorrect: false },
        { id: 'opt-3', text: 'ở đâu', isCorrect: false },
        { id: 'opt-4', text: 'bao nhiêu tuổi', isCorrect: false },
      ],
      correctAnswer: 'opt-1',
      explanation: '什么 (shénme) = cái gì, 名字 (míngzi) = tên.',
      vocabularyIds: ['vocab-hsk1-007', 'vocab-hsk1-008'],
      points: 10,
      difficulty: 'easy',
    },
  ],

  'lesson-hsk3-u1-l2': [
    { id: 'q-hsk3-l2-01', lessonId: 'lesson-hsk3-u1-l2', type: 'multiple_choice', order: 1, question: 'Bạn muốn nói “Tôi đặt phòng ba đêm” bằng tiếng Trung thế nào?', options: [{ id: 'a', text: '我住三天。', isCorrect: false }, { id: 'b', text: '我预订了三晚。', isCorrect: true }, { id: 'c', text: '我去了三晚。', isCorrect: false }, { id: 'd', text: '我买了三晚。', isCorrect: false }], correctAnswer: 'b', explanation: '预订 là đặt trước; 三晚 là ba đêm.', vocabularyIds: [], points: 10, difficulty: 'medium' },
    { id: 'q-hsk3-l2-02', lessonId: 'lesson-hsk3-u1-l2', type: 'multiple_choice', order: 2, question: 'Từ nào phù hợp với “yên tĩnh”?', options: [{ id: 'a', text: '安静', isCorrect: true }, { id: 'b', text: '热闹', isCorrect: false }, { id: 'c', text: '方便', isCorrect: false }, { id: 'd', text: '特别', isCorrect: false }], correctAnswer: 'a', explanation: '安静 nghĩa là yên tĩnh.', vocabularyIds: [], points: 10, difficulty: 'medium' },
    { id: 'q-hsk3-l2-03', lessonId: 'lesson-hsk3-u1-l2', type: 'multiple_choice', order: 3, question: '“早餐从七点开始” nghĩa là gì?', options: [{ id: 'a', text: 'Bữa tối bắt đầu lúc 7 giờ.', isCorrect: false }, { id: 'b', text: 'Bữa sáng bắt đầu lúc 7 giờ.', isCorrect: true }, { id: 'c', text: 'Phòng mở cửa lúc 7 giờ.', isCorrect: false }, { id: 'd', text: 'Tôi rời khách sạn lúc 7 giờ.', isCorrect: false }], correctAnswer: 'b', explanation: '早餐 là bữa sáng; 从...开始 là bắt đầu từ...', vocabularyIds: [], points: 10, difficulty: 'medium' },
  ],
  'lesson-hsk3-u2-l3': [
    { id: 'q-hsk3-l3-01', lessonId: 'lesson-hsk3-u2-l3', type: 'multiple_choice', order: 1, question: '“工作经验” nghĩa là gì?', options: [{ id: 'a', text: 'Kế hoạch công việc', isCorrect: false }, { id: 'b', text: 'Kinh nghiệm làm việc', isCorrect: true }, { id: 'c', text: 'Môi trường làm việc', isCorrect: false }, { id: 'd', text: 'Thời gian nghỉ', isCorrect: false }], correctAnswer: 'b', explanation: '工作经验 là kinh nghiệm làm việc.', vocabularyIds: [], points: 10, difficulty: 'medium' },
    { id: 'q-hsk3-l3-02', lessonId: 'lesson-hsk3-u2-l3', type: 'multiple_choice', order: 2, question: '“以前” thường dùng để nói về thời điểm nào?', options: [{ id: 'a', text: 'Trước đây', isCorrect: true }, { id: 'b', text: 'Ngày mai', isCorrect: false }, { id: 'c', text: 'Ngay bây giờ', isCorrect: false }, { id: 'd', text: 'Sau này', isCorrect: false }], correctAnswer: 'a', explanation: '以前 nghĩa là trước đây.', vocabularyIds: [], points: 10, difficulty: 'medium' },
    { id: 'q-hsk3-l3-03', lessonId: 'lesson-hsk3-u2-l3', type: 'multiple_choice', order: 3, question: 'Câu “你为什么想换工作？” hỏi điều gì?', options: [{ id: 'a', text: 'Bạn làm việc ở đâu?', isCorrect: false }, { id: 'b', text: 'Bạn làm việc bao lâu?', isCorrect: false }, { id: 'c', text: 'Vì sao bạn muốn đổi việc?', isCorrect: true }, { id: 'd', text: 'Bạn có muốn nghỉ phép?', isCorrect: false }], correctAnswer: 'c', explanation: '为什么 hỏi nguyên nhân; 换工作 là đổi việc.', vocabularyIds: [], points: 10, difficulty: 'medium' },
  ],
  'lesson-hsk3-u2-l4': [
    { id: 'q-hsk3-l4-01', lessonId: 'lesson-hsk3-u2-l4', type: 'multiple_choice', order: 1, question: '“打算” gần nghĩa nhất với từ nào?', options: [{ id: 'a', text: 'Dự định', isCorrect: true }, { id: 'b', text: 'Đã quên', isCorrect: false }, { id: 'c', text: 'Đang ngủ', isCorrect: false }, { id: 'd', text: 'Đã hoàn thành', isCorrect: false }], correctAnswer: 'a', explanation: '打算 dùng để nói dự định hoặc kế hoạch.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk3-l4-02', lessonId: 'lesson-hsk3-u2-l4', type: 'multiple_choice', order: 2, question: 'Trong “因为……所以……”, 因为 giới thiệu phần nào?', options: [{ id: 'a', text: 'Kết quả', isCorrect: false }, { id: 'b', text: 'Nguyên nhân', isCorrect: true }, { id: 'c', text: 'Địa điểm', isCorrect: false }, { id: 'd', text: 'Thời gian', isCorrect: false }], correctAnswer: 'b', explanation: '因为 giới thiệu nguyên nhân; 所以 giới thiệu kết quả.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk3-l4-03', lessonId: 'lesson-hsk3-u2-l4', type: 'multiple_choice', order: 3, question: '“提高口语” nghĩa là gì?', options: [{ id: 'a', text: 'Giảm thời gian học', isCorrect: false }, { id: 'b', text: 'Nâng cao khẩu ngữ', isCorrect: true }, { id: 'c', text: 'Đổi công việc', isCorrect: false }, { id: 'd', text: 'Đặt phòng', isCorrect: false }], correctAnswer: 'b', explanation: '提高 là nâng cao; 口语 là khẩu ngữ.', vocabularyIds: [], points: 10, difficulty: 'hard' },
  ],
  'lesson-hsk4-u1-l2': [
    { id: 'q-hsk4-l2-01', lessonId: 'lesson-hsk4-u1-l2', type: 'multiple_choice', order: 1, question: '“我认为” thường dùng để làm gì?', options: [{ id: 'a', text: 'Đưa ra quan điểm', isCorrect: true }, { id: 'b', text: 'Hỏi giá', isCorrect: false }, { id: 'c', text: 'Chào hỏi', isCorrect: false }, { id: 'd', text: 'Chỉ thời gian', isCorrect: false }], correctAnswer: 'a', explanation: '我认为 nghĩa là tôi cho rằng/tôi nghĩ rằng.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk4-l2-02', lessonId: 'lesson-hsk4-u1-l2', type: 'multiple_choice', order: 2, question: '“但是” biểu thị quan hệ nào?', options: [{ id: 'a', text: 'Nguyên nhân', isCorrect: false }, { id: 'b', text: 'Đối lập', isCorrect: true }, { id: 'c', text: 'Thời gian', isCorrect: false }, { id: 'd', text: 'Điều kiện', isCorrect: false }], correctAnswer: 'b', explanation: '但是 là nhưng, biểu thị sự đối lập.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk4-l2-03', lessonId: 'lesson-hsk4-u1-l2', type: 'multiple_choice', order: 3, question: 'Một ý kiến tốt trong tranh luận nên có gì?', options: [{ id: 'a', text: 'Lý do hoặc dẫn chứng', isCorrect: true }, { id: 'b', text: 'Chỉ một từ', isCorrect: false }, { id: 'c', text: 'Không cần giải thích', isCorrect: false }, { id: 'd', text: 'Chỉ dùng tiếng lóng', isCorrect: false }], correctAnswer: 'a', explanation: 'Lập luận rõ ràng thường cần lý do hoặc dẫn chứng.', vocabularyIds: [], points: 10, difficulty: 'hard' },
  ],
  'lesson-hsk5-u1-l2': [
    { id: 'q-hsk5-l2-01', lessonId: 'lesson-hsk5-u1-l2', type: 'multiple_choice', order: 1, question: '“报道” nghĩa là gì?', options: [{ id: 'a', text: 'Bản tin/bài đưa tin', isCorrect: true }, { id: 'b', text: 'Hợp đồng', isCorrect: false }, { id: 'c', text: 'Cuộc họp', isCorrect: false }, { id: 'd', text: 'Quảng cáo', isCorrect: false }], correctAnswer: 'a', explanation: '报道 thường chỉ bài đưa tin hoặc phóng sự/bản tin.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk5-l2-02', lessonId: 'lesson-hsk5-u1-l2', type: 'multiple_choice', order: 2, question: '“概括” nghĩa là gì?', options: [{ id: 'a', text: 'Tóm tắt/khái quát', isCorrect: true }, { id: 'b', text: 'Phủ nhận', isCorrect: false }, { id: 'c', text: 'So sánh giá', isCorrect: false }, { id: 'd', text: 'Đặt câu hỏi', isCorrect: false }], correctAnswer: 'a', explanation: '概括 là khái quát, tóm tắt nội dung chính.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk5-l2-03', lessonId: 'lesson-hsk5-u1-l2', type: 'multiple_choice', order: 3, question: 'Khi tóm tắt một bài báo, nên ưu tiên điều gì?', options: [{ id: 'a', text: 'Ý chính và thông tin cốt lõi', isCorrect: true }, { id: 'b', text: 'Mọi chi tiết nhỏ', isCorrect: false }, { id: 'c', text: 'Chỉ tiêu đề', isCorrect: false }, { id: 'd', text: 'Ý kiến không liên quan', isCorrect: false }], correctAnswer: 'a', explanation: 'Tóm tắt cần giữ lại ý chính và thông tin cốt lõi.', vocabularyIds: [], points: 10, difficulty: 'hard' },
  ],
  'lesson-hsk6-u1-l2': [
    { id: 'q-hsk6-l2-01', lessonId: 'lesson-hsk6-u1-l2', type: 'multiple_choice', order: 1, question: '“成语” nghĩa là gì?', options: [{ id: 'a', text: 'Thành ngữ', isCorrect: true }, { id: 'b', text: 'Tin tức', isCorrect: false }, { id: 'c', text: 'Hợp đồng', isCorrect: false }, { id: 'd', text: 'Phương tiện giao thông', isCorrect: false }], correctAnswer: 'a', explanation: '成语 là thành ngữ cố định, thường có bốn chữ.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk6-l2-02', lessonId: 'lesson-hsk6-u1-l2', type: 'multiple_choice', order: 2, question: '“深层含义” nói về điều gì?', options: [{ id: 'a', text: 'Tầng nghĩa sâu', isCorrect: true }, { id: 'b', text: 'Âm lượng', isCorrect: false }, { id: 'c', text: 'Tốc độ nói', isCorrect: false }, { id: 'd', text: 'Thời lượng học', isCorrect: false }], correctAnswer: 'a', explanation: '深层含义 là ý nghĩa sâu, tầng nghĩa sâu hơn của câu chữ.', vocabularyIds: [], points: 10, difficulty: 'hard' },
    { id: 'q-hsk6-l2-03', lessonId: 'lesson-hsk6-u1-l2', type: 'multiple_choice', order: 3, question: 'Khi dùng thành ngữ, yếu tố nào đặc biệt quan trọng?', options: [{ id: 'a', text: 'Ngữ cảnh', isCorrect: true }, { id: 'b', text: 'Màu sắc chữ', isCorrect: false }, { id: 'c', text: 'Độ dài tên người', isCorrect: false }, { id: 'd', text: 'Số lượng dấu câu', isCorrect: false }], correctAnswer: 'a', explanation: 'Thành ngữ cần phù hợp ngữ cảnh và sắc thái diễn đạt.', vocabularyIds: [], points: 10, difficulty: 'hard' },
  ],

};
