import { Vocabulary, GrammarPoint } from '../types/curriculum';

export const ALL_VOCABULARY: Vocabulary[] = [
  // HSK 1 Core Vocab
  {
    id: 'vocab-hsk1-001',
    hanzi: '你',
    pinyin: 'nǐ',
    meaningVi: 'bạn, anh, chị (ngôi thứ 2 số ít)',
    meaningEn: 'you',
    partOfSpeech: 'Đại từ',
    hskLevel: 1,
    exampleSentence: '你好！',
    examplePinyin: 'Nǐ hǎo!',
    exampleTranslation: 'Chào bạn!',
    tags: ['greetings', 'pronoun'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-002',
    hanzi: '好',
    pinyin: 'hǎo',
    meaningVi: 'tốt, đẹp, khỏe',
    meaningEn: 'good, fine',
    partOfSpeech: 'Tính từ',
    hskLevel: 1,
    exampleSentence: '我很好。',
    examplePinyin: 'Wǒ hěn hǎo.',
    exampleTranslation: 'Tôi rất khỏe.',
    tags: ['greetings', 'adjective'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-003',
    hanzi: '您',
    pinyin: 'nín',
    meaningVi: 'ngài, ông, bà (kính ngữ của 你)',
    meaningEn: 'you (respectful)',
    partOfSpeech: 'Đại từ',
    hskLevel: 1,
    exampleSentence: '老师，您好！',
    examplePinyin: 'Lǎoshī, nín hǎo!',
    exampleTranslation: 'Thưa thầy, chào thầy ạ!',
    tags: ['greetings', 'polite'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-004',
    hanzi: '谢谢',
    pinyin: 'xièxie',
    meaningVi: 'cảm ơn',
    meaningEn: 'thank you',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '谢谢你！',
    examplePinyin: 'Xièxie nǐ!',
    exampleTranslation: 'Cảm ơn bạn!',
    tags: ['polite', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-005',
    hanzi: '不客气',
    pinyin: 'bú kèqi',
    meaningVi: 'không có chi, đừng khách sáo',
    meaningEn: "you're welcome",
    partOfSpeech: 'Cụm từ',
    hskLevel: 1,
    exampleSentence: '不用谢，不客气。',
    examplePinyin: 'Bú yòng xiè, bú kèqi.',
    exampleTranslation: 'Đừng cảm ơn, không có chi đâu.',
    tags: ['polite', 'phrase'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-006',
    hanzi: '再见',
    pinyin: 'zàijiàn',
    meaningVi: 'tạm biệt, hẹn gặp lại',
    meaningEn: 'goodbye',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '明天见，再见！',
    examplePinyin: 'Míngtiān jiàn, zàijiàn!',
    exampleTranslation: 'Ngày mai gặp lại, tạm biệt!',
    tags: ['greetings', 'farewell'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-007',
    hanzi: '叫',
    pinyin: 'jiào',
    meaningVi: 'kêu, gọi, tên là',
    meaningEn: 'to be called',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '你叫什么名字？',
    examplePinyin: 'Nǐ jiào shénme míngzi?',
    exampleTranslation: 'Bạn tên là gì?',
    tags: ['introductions', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-008',
    hanzi: '名字',
    pinyin: 'míngzi',
    meaningVi: 'tên họ',
    meaningEn: 'name',
    partOfSpeech: 'Danh từ',
    hskLevel: 1,
    exampleSentence: '我的名字叫李明。',
    examplePinyin: 'Wǒ de míngzi jiào Lǐ Míng.',
    exampleTranslation: 'Tên tôi là Lý Minh.',
    tags: ['introductions', 'noun'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-009',
    hanzi: '是',
    pinyin: 'shì',
    meaningVi: 'là, phải, đúng',
    meaningEn: 'to be',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '我是越南人。',
    examplePinyin: 'Wǒ shì Yuènán rén.',
    exampleTranslation: 'Tôi là người Việt Nam.',
    tags: ['grammar', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-010',
    hanzi: '人',
    pinyin: 'rén',
    meaningVi: 'người',
    meaningEn: 'person, people',
    partOfSpeech: 'Danh từ',
    hskLevel: 1,
    exampleSentence: '他是中国人。',
    examplePinyin: 'Tā shì Zhōngguó rén.',
    exampleTranslation: 'Anh ấy là người Trung Quốc.',
    tags: ['noun', 'nationality'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-011',
    hanzi: '中国',
    pinyin: 'Zhōngguó',
    meaningVi: 'Trung Quốc',
    meaningEn: 'China',
    partOfSpeech: 'Danh từ riêng',
    hskLevel: 1,
    exampleSentence: '中国很大。',
    examplePinyin: 'Zhōngguó hěn dà.',
    exampleTranslation: 'Trung Quốc rất lớn.',
    tags: ['country', 'noun'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-012',
    hanzi: '吃',
    pinyin: 'chī',
    meaningVi: 'ăn',
    meaningEn: 'to eat',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '你想吃什么？',
    examplePinyin: 'Nǐ xiǎng chī shénme?',
    exampleTranslation: 'Bạn muốn ăn gì?',
    tags: ['daily', 'food', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-013',
    hanzi: '喝',
    pinyin: 'hē',
    meaningVi: 'uống',
    meaningEn: 'to drink',
    partOfSpeech: 'Động từ',
    hskLevel: 1,
    exampleSentence: '我喜欢喝中国茶。',
    examplePinyin: 'Wǒ xǐhuan hē Zhōngguó chá.',
    exampleTranslation: 'Tôi thích uống trà Trung Quốc.',
    tags: ['food', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-014',
    hanzi: '茶',
    pinyin: 'chá',
    meaningVi: 'trà, chè',
    meaningEn: 'tea',
    partOfSpeech: 'Danh từ',
    hskLevel: 1,
    exampleSentence: '请喝茶。',
    examplePinyin: 'Qǐng hē chá.',
    exampleTranslation: 'Mời uống trà.',
    tags: ['food', 'noun'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-015',
    hanzi: '多少',
    pinyin: 'duōshao',
    meaningVi: 'bao nhiêu',
    meaningEn: 'how many, how much',
    partOfSpeech: 'Đại từ nghi vấn',
    hskLevel: 1,
    exampleSentence: '这个多少钱？',
    examplePinyin: 'Zhè ge duōshao qián?',
    exampleTranslation: 'Cái này bao nhiêu tiền?',
    tags: ['shopping', 'question'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk1-016',
    hanzi: '钱',
    pinyin: 'qián',
    meaningVi: 'tiền',
    meaningEn: 'money',
    partOfSpeech: 'Danh từ',
    hskLevel: 1,
    exampleSentence: '我有钱。',
    examplePinyin: 'Wǒ yǒu qián.',
    exampleTranslation: 'Tôi có tiền.',
    tags: ['shopping', 'noun'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 2 Core Vocab
  {
    id: 'vocab-hsk2-001',
    hanzi: '起床',
    pinyin: 'qǐchuáng',
    meaningVi: 'thức dậy, rời giường',
    meaningEn: 'to get out of bed',
    partOfSpeech: 'Động từ ly hợp',
    hskLevel: 2,
    exampleSentence: '我早上七点起床。',
    examplePinyin: 'Wǒ zǎoshang qī diǎn qǐchuáng.',
    exampleTranslation: 'Tôi thức dậy lúc 7 giờ sáng.',
    tags: ['routine', 'verb'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk2-002',
    hanzi: '跑步',
    pinyin: 'pǎobù',
    meaningVi: 'chạy bộ',
    meaningEn: 'to run, jog',
    partOfSpeech: 'Động từ ly hợp',
    hskLevel: 2,
    exampleSentence: '他每天都去跑步。',
    examplePinyin: 'Tā měi tiān dōu qù pǎobù.',
    exampleTranslation: 'Anh ấy ngày nào cũng đi chạy bộ.',
    tags: ['sports', 'routine'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk2-003',
    hanzi: '正在',
    pinyin: 'zhèngzài',
    meaningVi: 'đang (chỉ hành động đang diễn ra)',
    meaningEn: 'in the process of',
    partOfSpeech: 'Phó từ',
    hskLevel: 2,
    exampleSentence: '我正在学习汉语。',
    examplePinyin: 'Wǒ zhèngzài xuéxí Hànyǔ.',
    exampleTranslation: 'Tôi đang học tiếng Trung.',
    tags: ['grammar', 'time'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk2-004',
    hanzi: '地铁',
    pinyin: 'dìtiě',
    meaningVi: 'tàu điện ngầm',
    meaningEn: 'subway, metro',
    partOfSpeech: 'Danh từ',
    hskLevel: 2,
    exampleSentence: '我们坐地铁去吧。',
    examplePinyin: 'Wǒmen zuò dìtiě qù ba.',
    exampleTranslation: 'Chúng mình đi tàu điện ngầm nhé.',
    tags: ['transport', 'travel'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk2-005',
    hanzi: '左边',
    pinyin: 'zuǒbian',
    meaningVi: 'bên trái',
    meaningEn: 'left side',
    partOfSpeech: 'Danh từ phương vị',
    hskLevel: 2,
    exampleSentence: '学校在车站的左边。',
    examplePinyin: 'Xuéxiào zài chēzhàn de zuǒbian.',
    exampleTranslation: 'Trường học nằm ở bên trái nhà ga.',
    tags: ['direction'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk2-006',
    hanzi: '天气',
    pinyin: 'tiānqì',
    meaningVi: 'thời tiết',
    meaningEn: 'weather',
    partOfSpeech: 'Danh từ',
    hskLevel: 2,
    exampleSentence: '今天天气很好。',
    examplePinyin: 'Jīntiān tiānqì hěn hǎo.',
    exampleTranslation: 'Hôm nay thời tiết rất đẹp.',
    tags: ['weather'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 3 Core Vocab
  {
    id: 'vocab-hsk3-001',
    hanzi: '行李箱',
    pinyin: 'xínglixiāng',
    meaningVi: 'va li hành lý',
    meaningEn: 'luggage, suitcase',
    partOfSpeech: 'Danh từ',
    hskLevel: 3,
    exampleSentence: '我的行李箱太重了。',
    examplePinyin: 'Wǒ de xínglixiāng tài zhòng le.',
    exampleTranslation: 'Vali của tôi nặng quá.',
    tags: ['travel'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk3-002',
    hanzi: '经历',
    pinyin: 'jīnglì',
    meaningVi: 'trải nghiệm, trải qua',
    meaningEn: 'experience',
    partOfSpeech: 'Danh từ/Động từ',
    hskLevel: 3,
    exampleSentence: '这是一次难忘的经历。',
    examplePinyin: 'Zhè shì yí cì nánwàng de jīnglì.',
    exampleTranslation: 'Đây là một trải nghiệm khó quên.',
    tags: ['life', 'travel'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk3-003',
    hanzi: '面试',
    pinyin: 'miànshì',
    meaningVi: 'phỏng vấn',
    meaningEn: 'interview',
    partOfSpeech: 'Động từ/Danh từ',
    hskLevel: 3,
    exampleSentence: '明天上午我有一个面试。',
    examplePinyin: 'Míngtiān shàngwǔ wǒ yǒu yí gè miànshì.',
    exampleTranslation: 'Sáng mai tôi có một buổi phỏng vấn.',
    tags: ['work', 'interview'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  // HSK 4-6 Vocab
  {
    id: 'vocab-hsk4-001',
    hanzi: '适应',
    pinyin: 'shìyìng',
    meaningVi: 'thích nghi, quen với',
    meaningEn: 'to adapt to',
    partOfSpeech: 'Động từ',
    hskLevel: 4,
    exampleSentence: '我已经适应了这里的生活。',
    examplePinyin: 'Wǒ yǐjīng shìyìng le zhèlǐ de shēnghuó.',
    exampleTranslation: 'Tôi đã thích nghi với cuộc sống ở đây rồi.',
    tags: ['lifestyle'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk5-001',
    hanzi: '趋势',
    pinyin: 'qūshì',
    meaningVi: 'xu hướng, chiều hướng',
    meaningEn: 'trend, tendency',
    partOfSpeech: 'Danh từ',
    hskLevel: 5,
    exampleSentence: '数字化是未来的发展趋势。',
    examplePinyin: 'Shùzìhuà shì wèilái de fāzhǎn qūshì.',
    exampleTranslation: 'Số hóa là xu hướng phát triển của tương lai.',
    tags: ['business', 'tech'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'vocab-hsk6-001',
    hanzi: '络绎不绝',
    pinyin: 'luòyì-bùjué',
    meaningVi: 'nườm nượp không dứt, tấp nập',
    meaningEn: 'in an endless stream',
    partOfSpeech: 'Thành ngữ',
    hskLevel: 6,
    exampleSentence: '来参观的游客络绎不绝。',
    examplePinyin: 'Lái cānguān de yóukè luòyì-bùjué.',
    exampleTranslation: 'Du khách đến tham quan nườm nượp không dứt.',
    tags: ['idiom', 'chengyu'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];

export const ALL_GRAMMAR_POINTS: GrammarPoint[] = [
  {
    id: 'grammar-hsk1-001',
    level: 1,
    title: 'Câu phán đoán với 是 (shì)',
    pattern: 'Chủ ngữ + 是 + Danh từ/Cụm danh từ',
    explanationVi: 'Được dùng để biểu thị quan hệ nhận định, tương đương với từ "là" trong tiếng Việt.',
    examples: [
      {
        chinese: '我是学生。',
        pinyin: 'Wǒ shì xuésheng.',
        translationVi: 'Tôi là học sinh.',
        explanation: 'Khẳng định danh tính bản thân.',
      },
      {
        chinese: '他是中国人。',
        pinyin: 'Tā shì Zhōngguó rén.',
        translationVi: 'Anh ấy là người Trung Quốc.',
        explanation: 'Khẳng định quốc tịch.',
      },
    ],
    commonMistakes: ['Không dùng 是 trước tính từ (Ví dụ sai: 我是很好 -> Đúng: 我很好)'],
    difficulty: 'beginner',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk1-002',
    level: 1,
    title: 'Trợ từ nghi vấn 吗 (ma)',
    pattern: 'Câu trần thuật + 吗？',
    explanationVi: 'Đặt ở cuối câu trần thuật để biến câu đó thành câu hỏi Có/Không (Yes/No question).',
    examples: [
      {
        chinese: '你好吗？',
        pinyin: 'Nǐ hǎo ma?',
        translationVi: 'Bạn khỏe không?',
      },
      {
        chinese: '你是老师吗？',
        pinyin: 'Nǐ shì lǎoshī ma?',
        translationVi: 'Bạn có phải là giáo viên không?',
      },
    ],
    commonMistakes: ['Không dùng 吗 khi câu đã có đại từ nghi vấn như 什么, 谁, 哪儿.'],
    difficulty: 'beginner',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk1-003',
    level: 1,
    title: 'Đại từ nghi vấn 什么 (shénme)',
    pattern: 'Động từ + 什么 (+ Danh từ)？',
    explanationVi: 'Dùng để hỏi "cái gì", "gì". Có thể đứng một mình sau động từ hoặc đứng trước danh từ làm định ngữ.',
    examples: [
      {
        chinese: '你叫什么名字？',
        pinyin: 'Nǐ jiào shénme míngzi?',
        translationVi: 'Bạn tên là gì?',
      },
      {
        chinese: '你想吃什么？',
        pinyin: 'Nǐ xiǎng chī shénme?',
        translationVi: 'Bạn muốn ăn gì?',
      },
    ],
    difficulty: 'beginner',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk2-001',
    level: 2,
    title: 'Hành động đang tiếp diễn với 正在 (zhèngzài)',
    pattern: 'Chủ ngữ + 正在/在 + Động từ (+ Tân ngữ) + (呢)',
    explanationVi: 'Biểu thị một hành động hoặc trạng thái đang xảy ra tại thời điểm nói, tương đương với "đang" trong tiếng Việt.',
    examples: [
      {
        chinese: '我正在吃饭呢。',
        pinyin: 'Wǒ zhèngzài chīfàn ne.',
        translationVi: 'Tôi đang ăn cơm.',
      },
      {
        chinese: '老师在看书。',
        pinyin: 'Lǎoshī zài kànshū.',
        translationVi: 'Thầy giáo đang đọc sách.',
      },
    ],
    commonMistakes: ['Phủ định dùng 没有 hoặc 没在, tuyệt đối không dùng 不正在.'],
    difficulty: 'beginner',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk2-002',
    level: 2,
    title: 'Trợ từ động thái 了 (le) biểu thị hoàn thành',
    pattern: 'Động từ + 了 (+ Tân ngữ)',
    explanationVi: 'Nhấn mạnh hành động đã xảy ra hoặc hoàn tất, không hoàn toàn đồng nghĩa với thì quá khứ.',
    examples: [
      {
        chinese: '我买了一本书。',
        pinyin: 'Wǒ mǎi le yì běn shū.',
        translationVi: 'Tôi đã mua một quyển sách.',
      },
      {
        chinese: '他去北京了。',
        pinyin: 'Tā qù Běijīng le.',
        translationVi: 'Anh ấy đi Bắc Kinh rồi.',
      },
    ],
    commonMistakes: ['Phủ định không dùng 不 và không giữ 了 (Đúng: 我没买书).'],
    difficulty: 'intermediate',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk3-001',
    level: 3,
    title: 'Trợ từ động thái 过 (guo) chỉ trải nghiệm',
    pattern: 'Động từ + 过 (+ Tân ngữ)',
    explanationVi: 'Dùng để nhấn mạnh ai đó đã từng có trải nghiệm hoặc kinh nghiệm làm việc gì đó trong quá khứ.',
    examples: [
      {
        chinese: '我去过中国。',
        pinyin: 'Wǒ qù guo Zhōngguó.',
        translationVi: 'Tôi từng đi Trung Quốc.',
      },
      {
        chinese: '你吃过烤鸭吗？',
        pinyin: 'Nǐ chī guo kǎoyā ma?',
        translationVi: 'Bạn từng ăn vịt quay chưa?',
      },
    ],
    difficulty: 'intermediate',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
  {
    id: 'grammar-hsk4-001',
    level: 4,
    title: 'Câu chữ 把 (bǎ) xử lý tân ngữ',
    pattern: 'Chủ ngữ + 把 + Tân ngữ + Động từ + Thành phần khác',
    explanationVi: 'Nhấn mạnh sự tác động của chủ ngữ làm thay đổi vị trí, trạng thái hoặc tính chất của tân ngữ.',
    examples: [
      {
        chinese: '请把门关上。',
        pinyin: 'Qǐng bǎ mén guān shàng.',
        translationVi: 'Xin hãy đóng cửa lại.',
      },
      {
        chinese: '我已经把作业做完了。',
        pinyin: 'Wǒ yǐjīng bǎ zuòyè zuò wán le.',
        translationVi: 'Tôi đã làm xong bài tập rồi.',
      },
    ],
    difficulty: 'advanced',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },
];
