import type { UserProfile } from '../types';
import type { AIMemoryEntry, IntelligentMistake, LearnerProfile, StructuredLesson, TutorContext, DailyPersonalizedPlan } from '../learning/types';
import { learningEngine } from '../learning/engine';
import { storage } from './storage';
const KEY='lina_ai_memory_v1'; const now=()=>new Date().toISOString();
type MemoryState={profile:LearnerProfile|null;entries:AIMemoryEntry[];mistakes:IntelligentMistake[];conversationSummaries:string[]};
const blank=():MemoryState=>({profile:null,entries:[],mistakes:[],conversationSummaries:[]});
const read=():MemoryState=>storage.readJson(KEY, blank());
const write=(s:MemoryState)=>storage.writeJson(KEY,s);
export const aiMemoryService={
 getState:()=>read(),
 getLearnerProfile(profile:UserProfile):LearnerProfile{const s=read(),old=s.profile,l=learningEngine.getState(),w=learningEngine.weakAreas();const p:LearnerProfile={id:old?.id||'local-learner',displayName:profile.name,nativeLanguage:'vi',targetLanguage:'zh-CN',currentLevel:profile.level,hskLevel:profile.currentHsk||1,pinyinLevel:old?.pinyinLevel||'marks',learningGoal:profile.goal,dailyGoalMinutes:profile.dailyMinutes,streak:profile.streak,totalStudyMinutes:old?.totalStudyMinutes||0,vocabularyStats:{learned:profile.vocabularyLearned,mastered:l.reviews.filter(x=>x.mastery>=80).length,weak:w.vocabulary.length},grammarStats:{practiced:l.progress.grammarPractice,weak:w.grammar.length},pronunciationStats:{practiced:l.progress.pronunciationPractice,weakTones:w.tones.map(x=>x.original)},speakingStats:{sessions:l.progress.speakingPractice,confidence:Math.min(100,50+l.progress.speakingPractice*3)},listeningStats:{sessions:l.progress.listeningPractice,accuracy:Math.min(100,60+l.progress.listeningPractice*2)},readingStats:old?.readingStats||{sessions:0,accuracy:0},writingStats:old?.writingStats||{sessions:0,accuracy:0},weakAreas:[...w.grammar.map(x=>x.original),...w.vocabulary.map(x=>x.original),...w.tones.map(x=>x.original)].slice(0,8),strongAreas:l.reviews.filter(x=>x.mastery>=80).slice(0,5).map(x=>x.vocabularyId),recentLessons:l.progress.completedLessons.slice(-5),recentMistakes:l.mistakes.slice(0,8).map(x=>x.original),preferredTopics:old?.preferredTopics||['daily life','conversation'],lastActiveAt:now()};s.profile=p;write(s);return p;},
 rememberFact(kind:AIMemoryEntry['kind'],content:string,relatedVocabulary:string[]=[],relatedGrammar:string[]=[]){const s=read();const id=kind+':'+content.toLowerCase().slice(0,80);const old=s.entries.find(x=>x.id===id);s.entries.push({id,kind,content,relatedVocabulary,relatedGrammar,createdAt:old?.createdAt||now(),updatedAt:now()});s.entries=s.entries.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);write(s);},
 summarizeConversation(messages:string[]){const summary=messages.filter(Boolean).slice(-8).join(' | ').slice(0,700);if(!summary)return '';const s=read();s.conversationSummaries=[summary,...s.conversationSummaries].slice(0,8);write(s);return summary;},
 recordMistake(input:{type:IntelligentMistake['type'];originalInput:string;correctedInput:string;explanation:string;severity?:IntelligentMistake['severity'];relatedVocabulary?:string[];relatedGrammar?:string[];relatedPronunciation?:string[]}){const s=read();const m=s.mistakes.find(x=>x.type===input.type&&x.originalInput===input.originalInput&&x.correctedInput===input.correctedInput);if(m){m.frequency++;m.lastSeen=now();m.priority=Math.min(100,m.priority+10);m.resolved=false;}else{s.mistakes.push({id:'mistake-'+Date.now(),mistakeId:'mistake-'+Date.now(),type:input.type,original:input.originalInput,corrected:input.correctedInput,explanation:input.explanation,frequency:1,lastSeen:now(),mastery:0,originalInput:input.originalInput,correctedInput:input.correctedInput,severity:input.severity||'medium',firstSeen:now(),resolved:false,relatedVocabulary:input.relatedVocabulary||[],relatedGrammar:input.relatedGrammar||[],relatedPronunciation:input.relatedPronunciation||[],priority:50});}write(s);learningEngine.recordMistake(input.type,input.originalInput,input.correctedInput,input.explanation);return s.mistakes;},
 resolveMistake(id:string){const s=read(),m=s.mistakes.find(x=>x.mistakeId===id||x.id===id);if(m){m.resolved=true;m.mastery=Math.min(100,m.mastery+20);m.priority=Math.max(0,m.priority-25);write(s);}return m||null;},
 relevantMemory(topic:string){const s=read(),q=topic.toLowerCase();return s.entries.filter(x=>x.content.toLowerCase().includes(q)||x.relatedVocabulary?.some(v=>v.toLowerCase().includes(q))||x.relatedGrammar?.some(v=>v.toLowerCase().includes(q))).slice(0,8);},
 relevantMistakes(topic:string,currentLesson?:StructuredLesson|null){const s=read();return s.mistakes.filter(m=>!m.resolved||m.priority>25).filter(m=>!currentLesson||m.relatedVocabulary.length===0||currentLesson.vocabulary.some(v=>m.relatedVocabulary.includes(v.hanzi))).slice(0,8);},
 buildTutorContext(profile:UserProfile,topic:string,currentLesson:StructuredLesson|null,currentConversation:string[]):TutorContext{const learner=this.getLearnerProfile(profile);return {learner,relevantMemory:this.relevantMemory(topic),relevantMistakes:this.relevantMistakes(topic,currentLesson),currentLesson,currentConversation:currentConversation.slice(-6),difficulty:learningEngine.adaptiveDifficulty(currentLesson?.difficulty||1)};},
 generateDailyPlan(profile:UserProfile):DailyPersonalizedPlan{const b=learningEngine.dailyPlan(profile),p=this.getLearnerProfile(profile),m=read().mistakes.find(x=>!x.resolved);return {...b,reviewMinutes:5,weakVocabulary:p.weakAreas.slice(0,5),grammarPoint:m?.relatedGrammar?.[0]||null,pronunciationMinutes:3,conversationMinutes:5,miniQuiz:true,reason:m?'Ưu tiên lỗi lặp lại: '+m.originalInput:'Tiếp tục xây nền HSK 1 và ôn các mục đến hạn.'};},
 clearLearningMemory(){localStorage.removeItem(KEY);}, resetProgress(){learningEngine.resetProgress();this.clearLearningMemory();}
};