import type { UserProfile } from '../types';
import { HSK1_VOCABULARY } from '../learning/content';
import { learningEngine } from '../learning/engine';
import type { LessonGenerationParameters, LessonQuizQuestion, LessonSchema, LessonType, StructuredLesson } from '../learning/types';
import { aiMemoryService } from './aiMemory';
import { postJson } from './request';
import { cacheGet, cacheSet } from './cache';
import { appLogger } from './logger';

const knownVocabulary=new Map(HSK1_VOCABULARY.map(v=>[v.hanzi,v]));
const knownGrammar=new Set(['shi','jiao','ma','xiang','de','bu','zai']);
const knownHskLevels=new Set([1]);
export const validateGeneratedLesson=(lesson:LessonSchema,requestedLevel:string):string[]=>{const errors:string[]=[];const numeric=Number(String(requestedLevel).match(/\d+/)?.[0]||0);if(!lesson.id||!lesson.title||!lesson.description)errors.push('Thiếu metadata bài học.');if(!lesson.objectives?.length)errors.push('Lesson phải có objectives.');if(lesson.estimatedMinutes<5||lesson.estimatedMinutes>180)errors.push('estimatedMinutes ngoài phạm vi hợp lý.');if(!knownHskLevels.has(numeric))errors.push('Chưa có dữ liệu chuẩn HSK cho level này; không được tự gắn HSK level.');else if(lesson.hskLevel!==numeric)errors.push('HSK level không khớp dữ liệu chuẩn.');for(const v of lesson.vocabulary||[]){if(!v.hanzi||!v.pinyin||!v.vietnamese)errors.push('Vocabulary thiếu Chinese/Pinyin/Vietnamese.');const known=knownVocabulary.get(v.hanzi);if(numeric===1&&!known)errors.push('Từ '+v.hanzi+' chưa có trong content HSK1 chuẩn.');}for(const g of lesson.grammar||[]){if(!g.pattern||!g.meaning||!g.explanationVi)errors.push('Grammar thiếu pattern/meaning/explanation.');if(numeric===1&&!knownGrammar.has(g.id.replace(/^g-/,'')))errors.push('Grammar '+g.id+' chưa có trong content HSK1 chuẩn.');}for(const d of lesson.dialogue||[])if(!d.chinese||!d.pinyin||!d.vietnamese)errors.push('Dialogue phải có Chinese/Pinyin/Vietnamese.');for(const q of lesson.quiz||[])if(!q.question||!q.answer||!q.explanation||!q.skill)errors.push('Quiz question thiếu trường bắt buộc.');const words=(lesson.vocabulary||[]).map(v=>v.hanzi);const dialogueText=(lesson.dialogue||[]).map(d=>d.chinese).join('');if(words.length&&!words.some(w=>dialogueText.includes(w)))errors.push('Vocabulary không nhất quán với dialogue.');return errors;};
export const normalizeGeneratedLesson=(raw:any,params:LessonGenerationParameters):LessonSchema=>{const requested=Number(String(params.level).match(/\d+/)?.[0]||0);const hskLevel=knownHskLevels.has(requested)?requested:null;return{id:String(raw.id||('ai-'+Date.now())),title:String(raw.title||params.topic),description:String(raw.description||params.goal),hskLevel,level:String(raw.level||params.level),objectives:Array.isArray(raw.objectives)?raw.objectives.map(String):[params.goal],vocabulary:Array.isArray(raw.vocabulary)?raw.vocabulary.map((v:any)=>({...v,meaningVi:v.vietnamese||v.meaning||'',example:v.example||v.exampleChinese||'',examplePinyin:v.examplePinyin||'',exampleVi:v.exampleVietnamese||''})):[],grammar:Array.isArray(raw.grammar)?raw.grammar.map((g:any)=>({id:String(g.id||g.pattern||'ai-grammar'),pattern:String(g.pattern||g.structure||''),meaning:String(g.meaning||''),explanationVi:String(g.explanationVi||g.explanation||''),examples:Array.isArray(g.examples)?g.examples:[],commonMistakes:Array.isArray(g.commonMistakes)?g.commonMistakes:[],practiceQuestions:Array.isArray(g.practiceQuestions)?g.practiceQuestions:[]})):[],dialogue:Array.isArray(raw.dialogue)?raw.dialogue.map((d:any)=>({speaker:d.speaker==='learner'?'learner':'ai',chinese:String(d.chinese||''),pinyin:String(d.pinyin||''),vietnamese:String(d.vietnamese||d.translation||'')})):[],listening:Array.isArray(raw.listening)?raw.listening.map(String):[],speaking:Array.isArray(raw.speaking)?raw.speaking.map(String):[],reading:Array.isArray(raw.reading)?raw.reading.map(String):[],writing:Array.isArray(raw.writing)?raw.writing.map(String):[],roleplay:raw.roleplay||{title:'Roleplay',scenario:params.topic,prompt:params.goal,expectedPatterns:[]},quiz:Array.isArray(raw.quiz)?raw.quiz.map((q:any,i:number)=>({...q,id:String(q.id||('q-'+(i+1))),options:Array.isArray(q.options)?q.options.map(String):[],relatedVocabulary:Array.isArray(q.relatedVocabulary)?q.relatedVocabulary:[],relatedGrammar:Array.isArray(q.relatedGrammar)?q.relatedGrammar:[]})):[],review:Array.isArray(raw.review)?raw.review:learningEngine.reviewTypes(),estimatedMinutes:Number(raw.estimatedMinutes||params.duration),lessonType:(raw.lessonType||'mixed') as LessonType};};
export const lessonToStructured=(lesson:LessonSchema):StructuredLesson=>({id:lesson.id,hskLevel:lesson.hskLevel||0,lessonNumber:0,title:lesson.title,objective:lesson.description,vocabulary:lesson.vocabulary,grammar:lesson.grammar,dialogue:lesson.dialogue,listening:lesson.listening,speaking:lesson.speaking,roleplay:lesson.roleplay,review:lesson.review,difficulty:3});
export class LessonEngine{async generateLesson(parameters:LessonGenerationParameters):Promise<LessonSchema>{const cacheKey='lesson:'+JSON.stringify(parameters);const cached=cacheGet<LessonSchema>(cacheKey);if(cached)return cached;try{const data=await postJson<any>('/api/ai/lesson',{...parameters,canonicalVocabulary:parameters.level==='HSK 1'?HSK1_VOCABULARY.map(v=>({id:v.id,hanzi:v.hanzi,pinyin:v.pinyin,vietnamese:v.vietnamese,hskLevel:v.hskLevel})):[]});const lesson=normalizeGeneratedLesson(data,parameters);const errors=validateGeneratedLesson(lesson,parameters.level);if(errors.length)throw new Error('Lesson validation failed: '+errors.slice(0,4).join(' '));cacheSet(cacheKey,lesson,30*60*1000);return lesson;}catch(error){appLogger.error('lesson-error',error);throw error;}}generateMicroLesson(topic:string,goal:string,profile:UserProfile,weaknesses:string[]=[]){return this.generateLesson({level:'HSK '+(profile.currentHsk||1),topic,goal,duration:5,learnerWeaknesses:weaknesses,targetVocabulary:[],targetGrammar:[]});}async generatePersonalizedLesson(profile:UserProfile){const memory=aiMemoryService.buildTutorContext(profile,'personalized lesson',null,[]);return this.generateLesson({level:'HSK '+(profile.currentHsk||1),topic:memory.learner.preferredTopics[0]||'Daily Life',goal:'Cải thiện điểm yếu gần đây',duration:Math.min(20,profile.dailyMinutes||15),learnerWeaknesses:[...memory.learner.weakAreas,...memory.relevantMistakes.map(m=>m.originalInput)],targetVocabulary:memory.relevantMistakes.flatMap(m=>m.relatedVocabulary),targetGrammar:memory.relevantMistakes.flatMap(m=>m.relatedGrammar)});}createQuiz(lesson:LessonSchema):LessonQuizQuestion[]{return lesson.quiz;}completeLesson(lesson:LessonSchema,results:{correctVocabulary?:string[];incorrectVocabulary?:string[];mistakes?:Array<{type:any;original:string;corrected:string;explanation:string}>;reviewRatings?:Array<{vocabularyId:string;rating:'again'|'hard'|'good'|'easy'}>}){learningEngine.startLesson(lesson.id);for(const section of ['vocabulary','grammar','listening','speaking','roleplay','review'] as const)learningEngine.completeSection(lesson.id,section);for(const id of results.correctVocabulary||[])learningEngine.review(id,'good');for(const id of results.incorrectVocabulary||[])learningEngine.review(id,'again');for(const m of results.mistakes||[])learningEngine.recordMistake(m.type,m.original,m.corrected,m.explanation);for(const r of results.reviewRatings||[])learningEngine.review(r.vocabularyId,r.rating);aiMemoryService.rememberFact('learning-history','Hoàn thành lesson: '+lesson.title,lesson.vocabulary.map(v=>v.hanzi));return learningEngine.getState();}}
export const lessonEngine=new LessonEngine();