export type RoleplayDifficulty = 'beginner'|'intermediate'|'advanced';
export type ImmersionLevel = 'beginner'|'intermediate'|'advanced';
export interface RoleplayScenario { id:string; scenario:string; context:string; character:string; learnerRole:string; aiRole:string; difficulty:RoleplayDifficulty; targetVocabulary:string[]; targetGrammar:string[]; successCriteria:string[]; }
export interface RoleplayTurn { role:'user'|'assistant'; text:string; }
export interface RoleplaySession { scenario:RoleplayScenario; turns:RoleplayTurn[]; learnerFacts:string[]; choices:string[]; startedAt:string; completed:boolean; }
export interface RoleplaySummary { summary:string; vocabularyLearned:string[]; grammarLearned:string[]; mistakes:string[]; pronunciationIssues:string[]; usefulExpressions:string[]; suggestedReview:string[]; }
const S=(id:string,scenario:string,context:string,character:string,learnerRole:string,aiRole:string,difficulty:RoleplayDifficulty,targetVocabulary:string[],targetGrammar:string[],successCriteria:string[]):RoleplayScenario=>({id,scenario,context,character,learnerRole,aiRole,difficulty,targetVocabulary,targetGrammar,successCriteria});
export const ROLEPLAY_SCENARIOS:RoleplayScenario[]=[
S('meeting-new-person','Gặp người mới','Một buổi gặp mặt lần đầu. Hai người làm quen tự nhiên.','Lina là người bạn mới người Trung Quốc.','Người mới gặp','Người bạn mới','beginner',['你好','叫','名字','来自','认识'],['我叫…','你叫什么名字？'],['Tự giới thiệu tên','Hỏi một thông tin liên quan','Duy trì ít nhất 3 lượt']),
S('restaurant','Gọi món','Bạn đang gọi món tại một nhà hàng ở Trung Quốc.','Lina là nhân viên phục vụ.','Khách hàng','Nhân viên phục vụ','beginner',['菜单','要','吃','喝','谢谢','这个'],['我要…','我想要…','可以吗？'],['Gọi ít nhất một món','Nêu một lựa chọn đồ uống hoặc yêu cầu','Xác nhận đơn']),
S('shopping','Mua đồ','Bạn vào một cửa hàng và muốn chọn một món đồ.','Lina là nhân viên bán hàng.','Khách mua hàng','Nhân viên bán hàng','beginner',['喜欢','颜色','大','小','买','这个'],['我喜欢…','有没有…？','我要这个。'],['Nói món cần mua','Trao đổi một đặc điểm','Hoàn tất lựa chọn']),
S('asking-price','Hỏi giá','Bạn muốn biết giá một món đồ và hỏi thêm nếu cần.','Lina là người bán hàng.','Khách hàng','Người bán','beginner',['多少钱','块','贵','便宜','买'],['多少钱？','太…了','可以便宜一点吗？'],['Hỏi giá','Phản hồi giá','Đưa ra quyết định']),
S('asking-directions','Hỏi đường','Bạn đang ở một thành phố Trung Quốc và cần tìm một địa điểm.','Lina là người địa phương.','Khách hỏi đường','Người địa phương','intermediate',['哪里','怎么走','左边','右边','前面','地铁'],['怎么去…？','在…旁边','一直走'],['Nói nơi cần đến','Hiểu chỉ dẫn','Hỏi lại khi chưa rõ']),
S('taxi','Đi taxi','Bạn bắt taxi để đến một địa chỉ.','Lina là tài xế taxi.','Hành khách','Tài xế','intermediate',['出租车','到','地址','路口','多少钱'],['请到…','到…要多久？','到了吗？'],['Nói điểm đến','Trao đổi thời gian hoặc giá','Xác nhận điểm xuống']),
S('hotel','Khách sạn','Bạn làm thủ tục nhận phòng và hỏi một dịch vụ.','Lina là lễ tân khách sạn.','Khách lưu trú','Lễ tân','intermediate',['酒店','房间','预订','护照','早餐','Wi-Fi'],['我预订了…','有没有…？','需要…'],['Nhận phòng','Xác nhận thông tin','Hỏi một nhu cầu']),
S('airport','Sân bay','Bạn cần làm thủ tục và tìm cổng lên máy bay.','Lina là nhân viên sân bay.','Hành khách','Nhân viên sân bay','intermediate',['机场','登机牌','航班','登机口','行李'],['我的航班是…','在哪里？','几点登机？'],['Nói thông tin chuyến bay','Hỏi vị trí hoặc thời gian','Tiếp tục theo hướng dẫn']),
S('school','Trường học','Bạn gặp một bạn học và trao đổi về lớp học.','Lina là bạn cùng lớp.','Học sinh/sinh viên','Bạn cùng lớp','beginner',['学校','老师','课','同学','学习'],['我学习…','你觉得…怎么样？'],['Nói về môn học','Hỏi ý kiến','Phản hồi một câu']),
S('work','Công việc','Bạn trao đổi ngắn với đồng nghiệp Trung Quốc.','Lina là đồng nghiệp.','Đồng nghiệp','Đồng nghiệp','intermediate',['工作','公司','客户','会议','今天','明天'],['我负责…','我们需要…','什么时候…？'],['Nói công việc','Trao đổi kế hoạch','Đặt một câu hỏi']),
S('phone-call','Gọi điện','Bạn gọi điện để trao đổi một việc đơn giản.','Lina là người nhận cuộc gọi.','Người gọi','Người nhận cuộc gọi','intermediate',['喂','方便','电话','告诉','晚一点'],['你现在方便吗？','我想…','可以请你…吗？'],['Mở đầu cuộc gọi','Nói mục đích','Kết thúc tự nhiên']),
S('clinic','Đi khám','Bạn mô tả một triệu chứng đơn giản tại phòng khám.','Lina là bác sĩ.','Bệnh nhân','Bác sĩ','intermediate',['医生','身体','哪里','疼','发烧','昨天'],['我觉得…','…疼','多久了？'],['Mô tả triệu chứng','Nói thời điểm bắt đầu','Trả lời câu hỏi tiếp theo']),
S('self-introduction','Giới thiệu bản thân','Một cuộc gặp đầu tiên trong môi trường học tập hoặc công việc.','Lina là người mới quen.','Người giới thiệu','Người mới quen','beginner',['叫','来自','住','工作','学习','喜欢'],['我叫…','我是…','我喜欢…'],['Giới thiệu ít nhất 3 thông tin','Hỏi lại một thông tin','Duy trì hội thoại']),
S('family','Nói về gia đình','Bạn trò chuyện với một người bạn mới về gia đình.','Lina là người bạn mới.','Người học','Người bạn','beginner',['家','爸爸','妈妈','哥哥','姐姐','几口人'],['我家有…','我有…','一共有…'],['Nói quy mô gia đình','Nói ít nhất một thành viên','Phản hồi câu hỏi']),
S('hobbies','Nói về sở thích','Bạn trò chuyện sau giờ học về sở thích và thời gian rảnh.','Lina là bạn cùng lớp.','Người học','Bạn cùng lớp','beginner',['喜欢','看书','电影','音乐','运动','周末'],['我喜欢…','我常常…','因为…所以…'],['Nói một sở thích','Nói khi nào làm','Hỏi sở thích của đối phương'])
];
export const getRoleplayScenario=(id:string)=>ROLEPLAY_SCENARIOS.find(x=>x.id===id)||ROLEPLAY_SCENARIOS[0];
export class RoleplayEngine {
 createSession(scenario:RoleplayScenario):RoleplaySession{return {scenario,turns:[],learnerFacts:[],choices:[],startedAt:new Date().toISOString(),completed:false};}
 buildPromptContext(session:RoleplaySession,immersion:ImmersionLevel){const s=session.scenario;return {scenario:s.scenario,context:s.context,character:s.character,learnerRole:s.learnerRole,aiRole:s.aiRole,difficulty:immersion==='advanced'?'advanced':immersion==='intermediate'?'intermediate':s.difficulty,targetVocabulary:s.targetVocabulary,targetGrammar:s.targetGrammar,successCriteria:s.successCriteria,immersion,learnerFacts:session.learnerFacts,choices:session.choices};}
 updateSession(session:RoleplaySession,learnerText:string){const facts=this.extractFacts(learnerText);return {...session,turns:[...session.turns,{role:'user',text:learnerText}],learnerFacts:Array.from(new Set([...session.learnerFacts,...facts]))};}
 addAssistantTurn(session:RoleplaySession,text:string){return {...session,turns:[...session.turns,{role:'assistant',text}]};}
 extractFacts(text:string){const facts:string[]=[];const name=text.match(/(?:我叫|我的名字是)\s*([^，。,.!！?？]+)/);if(name?.[1])facts.push('Tên learner: '+name[1].trim());if(/我来自/.test(text))facts.push(text.slice(Math.max(0,text.indexOf('我来自')),Math.min(text.length,text.indexOf('我来自')+18)));return facts;}
 summarize(session:RoleplaySession,analysis:any):RoleplaySummary{return {summary:analysis?.summary||'Hoàn thành tình huống '+session.scenario.scenario+'.',vocabularyLearned:analysis?.vocabularyLearned||session.scenario.targetVocabulary.slice(0,5),grammarLearned:analysis?.grammarLearned||session.scenario.targetGrammar.slice(0,3),mistakes:analysis?.mistakes||[],pronunciationIssues:analysis?.pronunciationIssues||[],usefulExpressions:analysis?.usefulExpressions||[],suggestedReview:analysis?.suggestedReview||session.scenario.targetVocabulary.slice(0,5)};}
}
export const roleplayEngine=new RoleplayEngine();
